// Literal URLs let Vite publish every DOM asset, including nested icons and
// webp UI art (which is not an Engine GPU texture). Also works in Bun tests.
const urls: Record<string, string> = {
  'assets/music/bgm-camp.mp3': new URL('../assets/music/bgm-camp.mp3', import.meta.url).href,
  'assets/music/bgm-den.mp3': new URL('../assets/music/bgm-den.mp3', import.meta.url).href,
  'assets/scenes/ashen-reach.layout.json': new URL('../assets/scenes/ashen-reach.layout.json', import.meta.url).href,
  'assets/scenes/rogue-encampment.obstacles.json': new URL('../assets/scenes/rogue-encampment.obstacles.json', import.meta.url).href,
  'assets/ui/fonts/cinzel-latin-ext.woff2': new URL('../assets/ui/fonts/cinzel-latin-ext.woff2', import.meta.url).href,
  'assets/ui/fonts/cinzel-latin.woff2': new URL('../assets/ui/fonts/cinzel-latin.woff2', import.meta.url).href,
  'assets/ui/hud/ship/automap-frame.webp': new URL('../assets/ui/hud/ship/automap-frame.webp', import.meta.url).href,
  'assets/ui/hud/ship/automap-parchment.webp': new URL('../assets/ui/hud/ship/automap-parchment.webp', import.meta.url).href,
  'assets/ui/hud/ship/bag-slot-empty.webp': new URL('../assets/ui/hud/ship/bag-slot-empty.webp', import.meta.url).href,
  'assets/ui/hud/ship/bar-wing-left.png': new URL('../assets/ui/hud/ship/bar-wing-left.png', import.meta.url).href,
  'assets/ui/hud/ship/bar-wing-right.png': new URL('../assets/ui/hud/ship/bar-wing-right.png', import.meta.url).href,
  'assets/ui/hud/ship/equip-slot-empty.webp': new URL('../assets/ui/hud/ship/equip-slot-empty.webp', import.meta.url).href,
  'assets/ui/hud/ship/globe-frame-hp.png': new URL('../assets/ui/hud/ship/globe-frame-hp.png', import.meta.url).href,
  'assets/ui/hud/ship/globe-frame-mp.png': new URL('../assets/ui/hud/ship/globe-frame-mp.png', import.meta.url).href,
  'assets/ui/hud/ship/hotbar-backplate.png': new URL('../assets/ui/hud/ship/hotbar-backplate.png', import.meta.url).href,
  'assets/ui/hud/ship/hotbar-slot-active.webp': new URL('../assets/ui/hud/ship/hotbar-slot-active.webp', import.meta.url).href,
  'assets/ui/hud/ship/hotbar-slot-empty.webp': new URL('../assets/ui/hud/ship/hotbar-slot-empty.webp', import.meta.url).href,
  'assets/ui/hud/ship/panel-frame-character.webp': new URL('../assets/ui/hud/ship/panel-frame-character.webp', import.meta.url).href,
  'assets/ui/hud/ship/panel-frame-forge.webp': new URL('../assets/ui/hud/ship/panel-frame-forge.webp', import.meta.url).href,
  'assets/ui/hud/ship/panel-frame-inventory.webp': new URL('../assets/ui/hud/ship/panel-frame-inventory.webp', import.meta.url).href,
  'assets/ui/icons/amulet.png': new URL('../assets/ui/icons/amulet.png', import.meta.url).href,
  'assets/ui/icons/armor.png': new URL('../assets/ui/icons/armor.png', import.meta.url).href,
  'assets/ui/icons/belt.png': new URL('../assets/ui/icons/belt.png', import.meta.url).href,
  'assets/ui/icons/boots.png': new URL('../assets/ui/icons/boots.png', import.meta.url).href,
  'assets/ui/icons/cursors/attack.png': new URL('../assets/ui/icons/cursors/attack.png', import.meta.url).href,
  'assets/ui/icons/cursors/default.png': new URL('../assets/ui/icons/cursors/default.png', import.meta.url).href,
  'assets/ui/icons/cursors/interact.png': new URL('../assets/ui/icons/cursors/interact.png', import.meta.url).href,
  'assets/ui/icons/cursors/loot.png': new URL('../assets/ui/icons/cursors/loot.png', import.meta.url).href,
  'assets/ui/icons/cursors/portal.png': new URL('../assets/ui/icons/cursors/portal.png', import.meta.url).href,
  'assets/ui/icons/cursors/talk.png': new URL('../assets/ui/icons/cursors/talk.png', import.meta.url).href,
  'assets/ui/icons/gloves.png': new URL('../assets/ui/icons/gloves.png', import.meta.url).href,
  'assets/ui/icons/helm.png': new URL('../assets/ui/icons/helm.png', import.meta.url).href,
  'assets/ui/icons/offhand.png': new URL('../assets/ui/icons/offhand.png', import.meta.url).href,
  'assets/ui/icons/ring.png': new URL('../assets/ui/icons/ring.png', import.meta.url).href,
  'assets/ui/icons/skills/arc.png': new URL('../assets/ui/icons/skills/arc.png', import.meta.url).href,
  'assets/ui/icons/skills/blink.png': new URL('../assets/ui/icons/skills/blink.png', import.meta.url).href,
  'assets/ui/icons/skills/frost.png': new URL('../assets/ui/icons/skills/frost.png', import.meta.url).href,
  'assets/ui/icons/skills/magma.png': new URL('../assets/ui/icons/skills/magma.png', import.meta.url).href,
  'assets/ui/icons/weapon.png': new URL('../assets/ui/icons/weapon.png', import.meta.url).href,
  'assets/ui/intro-poster.jpg': new URL('../assets/ui/intro-poster.jpg', import.meta.url).href,
  'assets/ui/intro.mp4': new URL('../assets/ui/intro.mp4', import.meta.url).href,
  'assets/ui/shell/shell-btn-hover.webp': new URL('../assets/ui/shell/shell-btn-hover.webp', import.meta.url).href,
  'assets/ui/shell/shell-btn-idle.webp': new URL('../assets/ui/shell/shell-btn-idle.webp', import.meta.url).href,
  'assets/ui/shell/shell-btn-pressed.webp': new URL('../assets/ui/shell/shell-btn-pressed.webp', import.meta.url).href,
  'assets/ui/shell/shell-latch-hover.webp': new URL('../assets/ui/shell/shell-latch-hover.webp', import.meta.url).href,
  'assets/ui/shell/shell-latch-idle.webp': new URL('../assets/ui/shell/shell-latch-idle.webp', import.meta.url).href,
  'assets/ui/shell/shell-latch-pressed.webp': new URL('../assets/ui/shell/shell-latch-pressed.webp', import.meta.url).href,
  'assets/ui/shell/shell-plaque-wide.webp': new URL('../assets/ui/shell/shell-plaque-wide.webp', import.meta.url).href,
  'assets/ui/shell/shell-pv-fill.webp': new URL('../assets/ui/shell/shell-pv-fill.webp', import.meta.url).href,
  'assets/ui/shell/shell-pv-track.webp': new URL('../assets/ui/shell/shell-pv-track.webp', import.meta.url).href,
  'assets/ui/shell/shell-skip-hover.webp': new URL('../assets/ui/shell/shell-skip-hover.webp', import.meta.url).href,
  'assets/ui/shell/shell-skip-idle.webp': new URL('../assets/ui/shell/shell-skip-idle.webp', import.meta.url).href,
  'assets/ui/title_bg.jpg': new URL('../assets/ui/title_bg.jpg', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/fire_01.png': new URL('../assets/vfx/packs/kenney-particle-pack/fire_01.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/fire_02.png': new URL('../assets/vfx/packs/kenney-particle-pack/fire_02.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/flame_05.png': new URL('../assets/vfx/packs/kenney-particle-pack/flame_05.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/flame_06.png': new URL('../assets/vfx/packs/kenney-particle-pack/flame_06.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/muzzle_01.png': new URL('../assets/vfx/packs/kenney-particle-pack/muzzle_01.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/muzzle_02.png': new URL('../assets/vfx/packs/kenney-particle-pack/muzzle_02.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/muzzle_03.png': new URL('../assets/vfx/packs/kenney-particle-pack/muzzle_03.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/muzzle_04.png': new URL('../assets/vfx/packs/kenney-particle-pack/muzzle_04.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/muzzle_05.png': new URL('../assets/vfx/packs/kenney-particle-pack/muzzle_05.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/smoke_01.png': new URL('../assets/vfx/packs/kenney-particle-pack/smoke_01.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/smoke_02.png': new URL('../assets/vfx/packs/kenney-particle-pack/smoke_02.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/smoke_03.png': new URL('../assets/vfx/packs/kenney-particle-pack/smoke_03.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/smoke_04.png': new URL('../assets/vfx/packs/kenney-particle-pack/smoke_04.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/smoke_05.png': new URL('../assets/vfx/packs/kenney-particle-pack/smoke_05.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/smoke_06.png': new URL('../assets/vfx/packs/kenney-particle-pack/smoke_06.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/smoke_07.png': new URL('../assets/vfx/packs/kenney-particle-pack/smoke_07.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/smoke_08.png': new URL('../assets/vfx/packs/kenney-particle-pack/smoke_08.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/smoke_09.png': new URL('../assets/vfx/packs/kenney-particle-pack/smoke_09.png', import.meta.url).href,
  'assets/vfx/packs/kenney-particle-pack/smoke_10.png': new URL('../assets/vfx/packs/kenney-particle-pack/smoke_10.png', import.meta.url).href,
};

export function gameAssetUrl(path: string): string {
  const key = path.replace(/^\.\.?\//, '');
  return urls[key] ?? new URL('../' + key, import.meta.url).href;
}
