// AUTO-GENERATED by scripts/bake-sky.ts — do not edit by hand.
// Sub-asset GUIDs of the baked sky-dome GLB (content-derived; re-bake updates).
export const SKY_DOME_MESH_GUID = '0abdd602-9429-aedb-ad55-8caa3e21a49a';
export const SKY_DOME_MATERIAL_GUID = 'e16e3b74-c7d9-2d0e-2e83-4040d6676b3e';
