// AUTO-GENERATED by scripts/bake-volcano.ts — do not edit by hand.
// Irregular cone meshes + shared prop-den-slag lava material.

export type VolcanoVariant = {
  name: string;
  mesh: string;
  material: string;
  kind: string;
};

export const VOLCANO_VARIANTS: readonly VolcanoVariant[] = [
  {
    "name": "prop-volcano-01",
    "mesh": "f1d1e4f5-d13a-971c-0524-2020c782dadd",
    "material": "31bd7990-9af5-7b87-5d71-cb5a6bea3ad4",
    "kind": "peak"
  },
  {
    "name": "prop-volcano-02",
    "mesh": "c1fd73c3-f41b-2a30-e528-36b6c548eaf8",
    "material": "31bd7990-9af5-7b87-5d71-cb5a6bea3ad4",
    "kind": "peak"
  },
  {
    "name": "prop-volcano-03",
    "mesh": "66640f75-fc17-aa6a-32c5-d4b3d9302f4c",
    "material": "31bd7990-9af5-7b87-5d71-cb5a6bea3ad4",
    "kind": "blunt"
  },
  {
    "name": "prop-volcano-04",
    "mesh": "36bcf83d-f5d0-d855-5ae1-55fced4f2f8a",
    "material": "31bd7990-9af5-7b87-5d71-cb5a6bea3ad4",
    "kind": "ridge"
  },
  {
    "name": "prop-volcano-05",
    "mesh": "75dfdf8c-eda3-873e-1aef-a7e00f1c940d",
    "material": "31bd7990-9af5-7b87-5d71-cb5a6bea3ad4",
    "kind": "peak"
  },
  {
    "name": "prop-volcano-06",
    "mesh": "1bb18f2d-c388-1e7c-3364-16a30f94ab65",
    "material": "31bd7990-9af5-7b87-5d71-cb5a6bea3ad4",
    "kind": "blunt"
  },
  {
    "name": "prop-volcano-07",
    "mesh": "cfae93a5-338b-5a25-5512-1542c17d2f8b",
    "material": "31bd7990-9af5-7b87-5d71-cb5a6bea3ad4",
    "kind": "ridge"
  },
  {
    "name": "prop-volcano-08",
    "mesh": "dbaaa833-3e80-ea76-31bf-a70218a9beb8",
    "material": "31bd7990-9af5-7b87-5d71-cb5a6bea3ad4",
    "kind": "peak"
  }
] as const;

/** Shared 熔渣/lava material (prop-den-slag). */
export const SLAG_MATERIAL_GUID = '31bd7990-9af5-7b87-5d71-cb5a6bea3ad4';
