// Generated by `bun tools/terrain-gate.ts --write`. Do not hand-edit.
export const TERRAIN_ALBEDO_WINDOWS = {
  sampleCount: 161144,
  seed: 20260810,
  bareMix: { lo: 0.25190558, hi: 0.49452854, loPercentile: 55, hiPercentile: 90 },
  valleyShade: { lo: 0.20194142, hi: 0.40320529, loPercentile: 10, hiPercentile: 80 },
} as const;
