/**
 * MarsCraft -> forgeax-engine — composite unit models (Milestone M3)
 * =============================================================================
 * Port of the Three.js source `web/engine/UnitModels.ts` (3833 LOC, ~80
 * `THREE.Group` builders). forgeax has no THREE.Group, so we use **approach (A)
 * multi-entity models** (see the task brief + ENGINE-API-CHEATSHEET "Custom
 * geometry"):
 *
 *   - the unit's parent entity carries the engine `Transform` (world pos);
 *   - every model part is a **child entity** with engine `ChildOf(parent)` +
 *     its own local `Transform` (offset / scale / rotation) + `MeshFilter`
 *     (one of FOUR shared unit-primitive MeshAssets — box / sphere / cone /
 *     cylinder, built once by `makePrimitives` and reused across ALL parts of
 *     ALL units) + `MeshRenderer` (a per-color tinted material, cached).
 *
 * The engine's auto-registered `propagateTransforms` system composes each
 * child's local Transform with the parent's into a world matrix every frame, so
 * the composite moves/rotates as one and parts remain individually animatable
 * (forms / turrets in later milestones).
 *
 * ── Source geometry -> forgeax mapping ───────────────────────────────────────
 * The source builds parts with `addPart(group, geo, material, pos, scale?, rot?)`
 * where `geo` is a THREE primitive:
 *   BoxGeometry(w,h,d)            -> box(pos, [w,h,d], rot?)
 *   SphereGeometry(r,...)         -> sphere(pos, r, rot?)        (unit sphere d=1)
 *   ConeGeometry(r,h,seg)         -> cone(pos, r, h, rot?)       (unit cone d=1,h=1)
 *   CylinderGeometry(rT,rB,h,seg) -> cyl(pos, max(rT,rB), h, rot?)
 * The 4 shared primitives are UNIT-sized (box 1x1x1; sphere d=1; cone d=1,h=1;
 * cylinder d=1,h=1), so a part's source dimensions become its child Transform
 * scale. Source per-part rotations (incl. baked-in nested-group offsets/rots)
 * are flattened into each part's local rot/pos — faithful for static models.
 *
 * ── Coverage / simplifications ───────────────────────────────────────────────
 * Faithful per-unit part lists are ported for the M3 test army + a spread of
 * each race (see UNIT_PARTS). The remaining units fall back to a recognizable
 * silhouette generated by `fallbackParts(def)` keyed on category/size/race
 * (a body + race-flavored accents). Units whose source model relied on
 * animation rigs / nested groups beyond a static silhouette and were thus
 * simplified are noted in the port report (e.g. Siege Tank — static turret, no
 * deploy-pose rig; organic Zerg leg sub-groups — top-level legs only).
 */

import {
  Transform, MeshFilter, MeshRenderer,
  ChildOf,
  quat,
  type Handle, type MaterialAsset,
} from '@forgeax/engine-runtime';
import { type MeshAsset } from '@forgeax/engine-assets-runtime';
import {
  createBoxGeometry, createSphereGeometry, createConeGeometry, createCylinderGeometry,
} from '@forgeax/engine-geometry';
import { type EntityHandle, type World } from '@forgeax/engine-ecs';
import type { UnitDef } from '../data/units';

// =============================================================================
// Part spec
// =============================================================================

export type PartShape = 'box' | 'sphere' | 'cone' | 'cylinder';

/** A single model primitive, in unit-local space (Y up, +Z forward). */
export interface Part {
  shape: PartShape;
  /** RGB 0..1 (already converted from the source 0xRRGGBB). */
  color: [number, number, number];
  /** Local offset. */
  pos: [number, number, number];
  /** Local size — for box: [w,h,d]; sphere: [d,d,d]; cone/cyl: [d,h,d]. */
  scale: [number, number, number];
  /** Euler XYZ radians (applied as Z*Y*X via quats below). */
  rot?: [number, number, number];
  /** Emissive accent (glow) — skips lighting tint metalness, brightens color. */
  emissive?: boolean;
}

// hex 0xRRGGBB -> linear-ish [r,g,b] 0..1 (engine PBR baseColor is sRGB-ish here;
// the source fed raw hex to THREE which gamma-corrects — a plain /255 is close
// enough for the flat-shaded silhouette look and matches terrain/env tinting).
function rgb(hex: number): [number, number, number] {
  return [((hex >> 16) & 0xff) / 255, ((hex >> 8) & 0xff) / 255, (hex & 0xff) / 255];
}

// ── part builders (mirror source addPart with each THREE primitive) ──────────
function box(color: number | [number, number, number], pos: [number, number, number], size: [number, number, number], rot?: [number, number, number], emissive = false): Part {
  return { shape: 'box', color: Array.isArray(color) ? color : rgb(color), pos, scale: size, rot, emissive };
}
function sphere(color: number | [number, number, number], pos: [number, number, number], r: number, scale?: [number, number, number], rot?: [number, number, number], emissive = false): Part {
  const s: [number, number, number] = scale ? [2 * r * scale[0], 2 * r * scale[1], 2 * r * scale[2]] : [2 * r, 2 * r, 2 * r];
  return { shape: 'sphere', color: Array.isArray(color) ? color : rgb(color), pos, scale: s, rot, emissive };
}
function cone(color: number | [number, number, number], pos: [number, number, number], r: number, h: number, rot?: [number, number, number], emissive = false): Part {
  return { shape: 'cone', color: Array.isArray(color) ? color : rgb(color), pos, scale: [2 * r, h, 2 * r], rot, emissive };
}
function cyl(color: number | [number, number, number], pos: [number, number, number], r: number, h: number, rot?: [number, number, number], emissive = false): Part {
  return { shape: 'cylinder', color: Array.isArray(color) ? color : rgb(color), pos, scale: [2 * r, h, 2 * r], rot, emissive };
}

// =============================================================================
// Shared primitive meshes (built once, reused by every part of every unit)
// =============================================================================

export interface UnitPrimitives {
  box: Handle<'MeshAsset', 'shared'>;
  sphere: Handle<'MeshAsset', 'shared'>;
  cone: Handle<'MeshAsset', 'shared'>;
  cylinder: Handle<'MeshAsset', 'shared'>;
}

/**
 * Build + cache the 4 unit-sized primitive MeshAssets. Call ONCE per world in
 * bootstrap; pass the result to every `spawnUnitModel` so parts reuse them.
 */
export function makePrimitives(world: World): UnitPrimitives | null {
  const b = createBoxGeometry(1, 1, 1, 1, 1, 1);
  const s = createSphereGeometry(0.5, 12, 8);
  const c = createConeGeometry(0.5, 1, 8);
  const cy = createCylinderGeometry(0.5, 0.5, 1, 8);
  if (!b.ok || !s.ok || !c.ok || !cy.ok) {
    console.error('[marscraft] unit primitive geometry build failed');
    return null;
  }
  return {
    box: world.allocSharedRef('MeshAsset', b.value as MeshAsset),
    sphere: world.allocSharedRef('MeshAsset', s.value as MeshAsset),
    cone: world.allocSharedRef('MeshAsset', c.value as MeshAsset),
    cylinder: world.allocSharedRef('MeshAsset', cy.value as MeshAsset),
  };
}

// =============================================================================
// Material tinting (cached per packed color so parts share handles)
// =============================================================================

/** Mints a tinted PBR material handle from an [r,g,b] (closes over base GUID). */
export type TintFn = (rgb: [number, number, number], opts?: { metallic?: number; roughness?: number }) => Handle<'MaterialAsset', 'shared'>;

const matCache = new Map<string, Handle<'MaterialAsset', 'shared'>>();

function partMaterial(tint: TintFn, color: [number, number, number], emissive: boolean): Handle<'MaterialAsset', 'shared'> {
  // emissive accents read brighter + flatter; lit parts get a little metal.
  const key = `${color[0].toFixed(3)},${color[1].toFixed(3)},${color[2].toFixed(3)},${emissive ? 1 : 0}`;
  const hit = matCache.get(key);
  if (hit) return hit;
  const c: [number, number, number] = emissive
    ? [Math.min(1, color[0] * 1.4 + 0.2), Math.min(1, color[1] * 1.4 + 0.2), Math.min(1, color[2] * 1.4 + 0.2)]
    : color;
  const m = tint(c, emissive ? { metallic: 0, roughness: 1 } : { metallic: 0.2, roughness: 0.7 });
  matCache.set(key, m);
  return m;
}

/** Reset the per-color material cache (call between worlds if reused). */
export function resetUnitMaterialCache(): void {
  matCache.clear();
}

// =============================================================================
// Spawn a composite model under a parent entity (approach A)
// =============================================================================

const _q = quat.create();

/**
 * Spawn every part of `def`'s composite model as a child entity of `parent`.
 * `factionColor` is the packed 0xRRGGBB player color used wherever the source
 * passed `playerColor`. Returns the spawned child entity handles.
 */
export function spawnUnitModel(
  world: World,
  parent: EntityHandle,
  def: UnitDef,
  factionColor: number,
  prims: UnitPrimitives,
  tint: TintFn,
): EntityHandle[] {
  const parts = (UNIT_PARTS[def.typeId] ?? fallbackParts)(def, factionColor);
  // Uniform model scale: source model is authored ~unit-height ~1; def.modelSize
  // is the in-world render size. We scale the whole composite by modelSize.
  const k = def.modelSize;
  const children: EntityHandle[] = [];
  for (const p of parts) {
    const mesh =
      p.shape === 'box' ? prims.box :
      p.shape === 'sphere' ? prims.sphere :
      p.shape === 'cone' ? prims.cone :
      prims.cylinder;
    const mat = partMaterial(tint, p.color, p.emissive ?? false);
    // THREE's default Euler order is 'XYZ'; match it so ported rotations align.
    if (p.rot) quat.fromEuler(_q, p.rot[0], p.rot[1], p.rot[2], 'XYZ');
    const res = world.spawn(
      {
        component: Transform,
        data: {
          pos: [p.pos[0] * k, p.pos[1] * k, p.pos[2] * k],
          quat: p.rot ? [_q[0], _q[1], _q[2], _q[3]] : [0, 0, 0, 1],
          scale: [p.scale[0] * k, p.scale[1] * k, p.scale[2] * k],
        },
      },
      { component: MeshFilter, data: { assetHandle: mesh } },
      { component: MeshRenderer, data: { materials: [mat] } },
      { component: ChildOf, data: { parent } },
    );
    if (res.ok) children.push(res.value);
  }
  return children;
}

// =============================================================================
// Per-unit faithful part lists (keyed by typeId — mirrors source MODEL_CREATORS)
// =============================================================================
// `main` = the player/faction color (source `playerColor`). Shared accent
// colors mirror the source's per-builder palettes.

type PartFn = (def: UnitDef, color: number) => Part[];

const C_GRAY = 0x555555;
const C_DARKMETAL = 0x444444;
const C_BONE = 0xa09080;
const C_CARAPACE = 0x3a2318;
const C_GOLD = 0xddaa44;
const C_BLUEGLOW = 0x4488ff;

const UNIT_PARTS: Record<string, PartFn> = {
  // ── Terran ────────────────────────────────────────────────────────────────
  scv: (_d, c) => [
    box(c, [0, 0, 0], [0.5, 0.5, 0.4]),
    cyl(C_GRAY, [0.3, 0.05, 0.1], 0.06, 0.4, [Math.PI / 2, 0, 0]),
    cyl(C_GRAY, [-0.3, 0.05, 0.1], 0.06, 0.4, [Math.PI / 2, 0, 0]),
    sphere(0xffcc00, [0, 0.3, 0.15], 0.08, undefined, undefined, true),
  ],
  marine: (_d, c) => [
    box(c, [0, 0, 0], [0.45, 0.55, 0.35]),
    sphere(c, [0, 0.4, 0], 0.18),
    sphere(C_BLUEGLOW, [0, 0.4, 0.15], 0.1, undefined, undefined, true),
    cyl(C_GRAY, [0.25, 0.15, 0.15], 0.04, 0.5, [Math.PI / 2, 0, 0]),
    box(c, [-0.12, -0.4, 0], [0.12, 0.3, 0.12]),
    box(c, [0.12, -0.4, 0], [0.12, 0.3, 0.12]),
  ],
  firebat: (_d, c) => [
    box(c, [0, 0, 0], [0.55, 0.55, 0.4]),
    sphere(c, [0, 0.4, 0], 0.2),
    sphere(0xff4400, [0, 0.4, 0.15], 0.12, undefined, undefined, true),
    cyl(C_DARKMETAL, [0.32, 0.15, 0.15], 0.06, 0.4, [Math.PI / 2, 0, 0]),
    cyl(C_DARKMETAL, [-0.32, 0.15, 0.15], 0.06, 0.4, [Math.PI / 2, 0, 0]),
  ],
  marauder: (_d, c) => [
    box(c, [0, 0, 0], [0.65, 0.6, 0.45]),
    box(C_GRAY, [0, 0.1, 0.2], [0.7, 0.35, 0.2]),
    sphere(c, [0, 0.45, 0], 0.2),
    sphere(0xff6600, [0, 0.45, 0.15], 0.1, undefined, undefined, true),
    box(C_GRAY, [0.4, 0.25, 0], [0.25, 0.2, 0.25]),
    box(C_GRAY, [-0.4, 0.25, 0], [0.25, 0.2, 0.25]),
    cyl(C_DARKMETAL, [0.4, 0.05, 0.25], 0.08, 0.5, [Math.PI / 2, 0, 0]),
    box(c, [-0.15, -0.45, 0], [0.16, 0.35, 0.16]),
    box(c, [0.15, -0.45, 0], [0.16, 0.35, 0.16]),
  ],
  goliath: (_d, c) => [
    box(c, [0, 0.3, 0], [0.5, 0.4, 0.5]),
    box(0x44aaff, [0, 0.35, 0.26], [0.3, 0.15, 0.05], undefined, true),
    box(C_GRAY, [0.4, 0.4, 0], [0.15, 0.15, 0.2]),
    cyl(C_GRAY, [0.4, 0.4, 0.3], 0.04, 0.45, [Math.PI / 2, 0, 0]),
    cyl(C_GRAY, [0.4, 0.48, 0.3], 0.04, 0.45, [Math.PI / 2, 0, 0]),
    box(C_GRAY, [-0.4, 0.4, 0], [0.15, 0.15, 0.2]),
    cyl(C_GRAY, [-0.4, 0.4, 0.3], 0.04, 0.45, [Math.PI / 2, 0, 0]),
    cyl(C_GRAY, [-0.4, 0.48, 0.3], 0.04, 0.45, [Math.PI / 2, 0, 0]),
    box(c, [0.2, -0.1, 0], [0.12, 0.35, 0.12]),
    sphere(0x666666, [0.2, -0.28, 0], 0.06),
    box(c, [0.2, -0.5, 0.05], [0.14, 0.35, 0.14]),
    box(c, [-0.2, -0.1, 0], [0.12, 0.35, 0.12]),
    sphere(0x666666, [-0.2, -0.28, 0], 0.06),
    box(c, [-0.2, -0.5, 0.05], [0.14, 0.35, 0.14]),
  ],
  thor: (_d, c) => [
    box(c, [0, 0.2, 0], [0.8, 0.7, 0.6]),
    box(C_GRAY, [0, 0.3, 0.3], [0.85, 0.4, 0.25]),
    box(c, [0, 0.7, 0], [0.3, 0.25, 0.3]),
    box(0xff4400, [0, 0.7, 0.16], [0.2, 0.1, 0.05], undefined, true),
    box(C_GRAY, [0.55, 0.5, 0], [0.35, 0.25, 0.4]),
    cyl(C_DARKMETAL, [0.45, 0.65, 0.1], 0.04, 0.2, [Math.PI / 2, 0, 0]),
    cyl(C_DARKMETAL, [0.55, 0.65, 0.1], 0.04, 0.2, [Math.PI / 2, 0, 0]),
    cyl(C_DARKMETAL, [0.65, 0.65, 0.1], 0.04, 0.2, [Math.PI / 2, 0, 0]),
    box(C_GRAY, [-0.55, 0.5, 0], [0.35, 0.25, 0.4]),
    cyl(C_DARKMETAL, [-0.55, 0.5, 0.35], 0.06, 0.5, [Math.PI / 2, 0, 0]),
    box(c, [0.5, -0.05, 0], [0.15, 0.45, 0.15]),
    box(c, [-0.5, -0.05, 0], [0.15, 0.45, 0.15]),
    box(c, [0.25, -0.5, 0], [0.2, 0.5, 0.2]),
    box(c, [-0.25, -0.5, 0], [0.2, 0.5, 0.2]),
    cyl(0xff6600, [0.2, 0.5, -0.35], 0.08, 0.15, undefined, true),
    cyl(0xff6600, [-0.2, 0.5, -0.35], 0.08, 0.15, undefined, true),
  ],
  wraith: (_d, c) => [
    box(c, [0, 0, 0], [0.35, 0.15, 0.8]),
    sphere(0x44aaff, [0, 0.08, 0.25], 0.12, [1, 0.6, 1.2], undefined, true),
    box(C_GRAY, [0.35, -0.02, -0.1], [0.6, 0.03, 0.35]),
    box(C_GRAY, [-0.35, -0.02, -0.1], [0.6, 0.03, 0.35]),
    box(C_GRAY, [0.7, 0.02, -0.15], [0.15, 0.03, 0.2]),
    box(C_GRAY, [-0.7, 0.02, -0.15], [0.15, 0.03, 0.2]),
    cyl(0xff6600, [0.12, 0, -0.45], 0.08, 0.15, [Math.PI / 2, 0, 0], true),
    cyl(0xff6600, [-0.12, 0, -0.45], 0.08, 0.15, [Math.PI / 2, 0, 0], true),
    cyl(C_GRAY, [0, -0.05, 0.45], 0.03, 0.2, [Math.PI / 2, 0, 0]),
  ],
  raider: (_d, c) => [
    box(c, [0, 0, -0.08], [0.38, 0.5, 0.3]),
    sphere(c, [0, 0.35, -0.08], 0.14),
    sphere(0xff4400, [0, 0.35, 0.05], 0.08, undefined, undefined, true),
    cyl(0xcc4400, [0, 0.2, -0.28], 0.1, 0.35),
    sphere(0xff6600, [0, 0.2, -0.45], 0.08, undefined, undefined, true),
    cyl(C_GRAY, [0.2, 0.1, 0.1], 0.05, 0.25, [Math.PI / 2, 0, 0]),
    cyl(C_GRAY, [-0.2, 0.1, 0.1], 0.05, 0.25, [Math.PI / 2, 0, 0]),
    box(c, [-0.1, -0.38, -0.12], [0.1, 0.22, 0.12]),
    box(c, [0.1, -0.38, -0.12], [0.1, 0.22, 0.12]),
  ],
  ghost: (_d, _c) => {
    const dark = 0x2a2a35;
    return [
      box(dark, [0, 0, 0], [0.4, 0.55, 0.32]),
      sphere(dark, [0, 0.38, 0], 0.16),
      sphere(0x334466, [0, 0.38, 0.14], 0.1, undefined, undefined, true),
      box(dark, [0.28, 0.3, 0], [0.08, 0.06, 0.12]),
      sphere(C_BLUEGLOW, [0.28, 0.32, 0.06], 0.04, undefined, undefined, true),
      box(dark, [-0.28, 0.3, 0], [0.08, 0.06, 0.12]),
      sphere(C_BLUEGLOW, [-0.28, 0.32, 0.06], 0.04, undefined, undefined, true),
      box(0x333344, [0, 0.15, -0.2], [0.25, 0.2, 0.15]),
      cyl(0x222222, [0.22, 0.1, 0.2], 0.025, 0.55, [Math.PI / 2, 0, 0]),
      box(dark, [-0.1, -0.42, 0], [0.1, 0.32, 0.1]),
      box(dark, [0.1, -0.42, 0], [0.1, 0.32, 0.1]),
    ];
  },
  // Siege Tank — SIMPLIFIED: static turret + barrel + 4 track pods. The source
  // uses a nested deploy-pose rig (applyPose/formAnimator); the M3 static model
  // keeps the recognizable chassis/turret/rail silhouette without the rig.
  tank: (_d, c) => {
    const metal = 0x555566, darkMetal = 0x222222;
    const trackPod = (x: number, z: number): Part[] => [
      box(darkMetal, [x, -0.1, z], [0.25, 0.3, 0.7]),
      box(c, [x, 0.08, z], [0.27, 0.08, 0.5]),
      box(metal, [x, -0.05, z], [0.3, 0.2, 0.4]),
    ];
    return [
      box(metal, [0, 0, 0], [0.7, 0.25, 0.9]),
      box(c, [0, 0.1, 0.4], [0.5, 0.15, 0.4]),
      box(metal, [0, 0.1, -0.4], [0.5, 0.15, 0.3]),
      ...trackPod(-0.55, 0.45), ...trackPod(0.55, 0.45),
      ...trackPod(-0.55, -0.45), ...trackPod(0.55, -0.45),
      box(metal, [0, 0.3, -0.1], [0.6, 0.2, 0.6]),
      box(c, [0, 0.45, -0.1], [0.4, 0.1, 0.4]),
      box(metal, [-0.06, 0.4, 0.4], [0.12, 0.15, 0.8]),
      box(metal, [0.06, 0.4, 0.4], [0.12, 0.15, 0.8]),
      cyl(0x22ff22, [0, 0.4, 0.9], 0.04, 1.0, [Math.PI / 2, 0, 0], true),
    ];
  },
  medivac: (_d, c) => [
    sphere(c, [0, 0, 0], 0.45, [1.1, 0.7, 1.3]),
    sphere(0x44aaff, [0, 0.1, 0.35], 0.14, undefined, undefined, true),
    box(0xcc2222, [0, 0.35, 0], [0.18, 0.06, 0.18]),
    box(0xcc2222, [0, 0.35, 0], [0.06, 0.18, 0.18]),
    cyl(C_GRAY, [0.42, -0.05, -0.1], 0.08, 0.3, [0, 0, Math.PI / 2]),
    cyl(C_GRAY, [-0.42, -0.05, -0.1], 0.08, 0.3, [0, 0, Math.PI / 2]),
    cyl(0xff6600, [0.45, 0, -0.4], 0.06, 0.15, [Math.PI / 2, 0, 0], true),
    cyl(0xff6600, [-0.45, 0, -0.4], 0.06, 0.15, [Math.PI / 2, 0, 0], true),
  ],

  // ── Zerg ───────────────────────────────────────────────────────────────────
  drone: (_d, c) => [
    sphere(c, [0, 0, 0], 0.3, [1, 0.6, 1.2]),
    cone(0xcc3300, [0.15, 0.2, 0.2], 0.04, 0.25, undefined, true),
    cone(0xcc3300, [-0.15, 0.2, 0.2], 0.04, 0.25, undefined, true),
  ],
  zergling: (_d, c) => [
    box(c, [0, 0.2, 0], [0.22, 0.2, 0.4], [0.2, 0, 0]),
    box(C_CARAPACE, [0, 0.3, 0.05], [0.28, 0.12, 0.25], [0.25, 0, 0]),
    box(C_CARAPACE, [0, 0.25, -0.15], [0.24, 0.12, 0.2], [0.15, 0, 0]),
    cone(C_CARAPACE, [0, 0.15, -0.35], 0.08, 0.25, [-1.2, 0, 0]),
    box(C_CARAPACE, [0, 0.28, 0.35], [0.14, 0.08, 0.35], [0.15, 0, 0]),
    box(c, [0, 0.2, 0.33], [0.12, 0.08, 0.32], [0.15, 0, 0]),
    sphere(0xffaa00, [0.06, 0.24, 0.43], 0.02, undefined, undefined, true),
    sphere(0xffaa00, [-0.06, 0.24, 0.43], 0.02, undefined, undefined, true),
    cone(C_CARAPACE, [0.12, 0.4, -0.05], 0.05, 0.35, [-0.6, 0, -0.4]),
    cone(C_CARAPACE, [-0.12, 0.4, -0.05], 0.05, 0.35, [-0.6, 0, 0.4]),
    // front claws (group baked to top level)
    box(C_CARAPACE, [0.18, 0.37, 0.30], [0.08, 0.15, 0.12], [0.4, 0.2, 0]),
    cone(C_BONE, [0.20, 0.20, 0.43], 0.03, 0.15, [1.2, 0, 0]),
    box(C_CARAPACE, [-0.18, 0.37, 0.30], [0.08, 0.15, 0.12], [0.4, -0.2, 0]),
    cone(C_BONE, [-0.20, 0.20, 0.43], 0.03, 0.15, [1.2, 0, 0]),
    // hind legs
    box(C_CARAPACE, [0.30, 0.33, -0.12], [0.12, 0.22, 0.15], [-0.5, 0, 0]),
    box(c, [0.30, 0.23, -0.20], [0.08, 0.2, 0.08], [0.4, 0, 0]),
    box(C_CARAPACE, [-0.30, 0.33, -0.12], [0.12, 0.22, 0.15], [-0.5, 0, 0]),
    box(c, [-0.30, 0.23, -0.20], [0.08, 0.2, 0.08], [0.4, 0, 0]),
  ],
  roach: (_d, c) => [
    box(c, [0, 0.2, 0], [0.3, 0.25, 0.5], [0.1, 0, 0]),
    box(C_CARAPACE, [0, 0.35, 0.1], [0.45, 0.1, 0.35], [0.2, 0, 0]),
    box(C_CARAPACE, [0, 0.4, -0.1], [0.35, 0.1, 0.3], [0.1, 0, 0]),
    box(C_CARAPACE, [0, 0.37, -0.3], [0.2, 0.1, 0.25], [-0.1, 0, 0]),
    cone(C_BONE, [0, 0.45, 0.15], 0.06, 0.2, [-0.6, 0, 0]),
    cone(C_BONE, [0.08, 0.47, 0], 0.06, 0.2, [-0.5, 0, 0]),
    cone(C_BONE, [-0.08, 0.47, 0], 0.06, 0.2, [-0.5, 0, 0]),
    box(C_CARAPACE, [0, 0.15, 0.35], [0.2, 0.15, 0.2], [-0.2, 0, 0]),
    box(c, [0, 0.1, 0.4], [0.12, 0.08, 0.22], [-0.2, 0, 0]),
    sphere(0xff6600, [0.08, 0.17, 0.45], 0.04, undefined, undefined, true),
    sphere(0xff6600, [-0.08, 0.17, 0.45], 0.04, undefined, undefined, true),
    // 4 ground legs (baked group offset xSign*0.15,0.15,z + part)
    box(C_CARAPACE, [0.23, 0.20, 0.05], [0.15, 0.08, 0.08], [0, 0.2, 0.4]),
    box(C_CARAPACE, [-0.23, 0.20, 0.05], [0.15, 0.08, 0.08], [0, -0.2, -0.4]),
    box(C_CARAPACE, [0.23, 0.20, -0.2], [0.15, 0.08, 0.08], [0, -0.3, 0.4]),
    box(C_CARAPACE, [-0.23, 0.20, -0.2], [0.15, 0.08, 0.08], [0, 0.3, -0.4]),
    cone(C_BONE, [0.38, 0.10, 0.05], 0.04, 0.25),
    cone(C_BONE, [-0.38, 0.10, 0.05], 0.04, 0.25),
  ],
  hydralisk: (_d, c) => [
    // serpentine body
    box(c, [0, 0.25, -0.1], [0.25, 0.3, 0.5], [0.1, 0, 0]),
    cone(c, [0, 0.5, -0.35], 0.12, 0.4, [-0.3, 0, 0]),
    // hood of spines
    cone(C_BONE, [0, 0.65, 0.05], 0.04, 0.3, [-0.4, 0, 0]),
    cone(C_BONE, [0.12, 0.6, 0.05], 0.04, 0.28, [-0.4, 0, -0.3]),
    cone(C_BONE, [-0.12, 0.6, 0.05], 0.04, 0.28, [-0.4, 0, 0.3]),
    // head
    box(C_CARAPACE, [0, 0.5, 0.2], [0.16, 0.14, 0.2], [0.2, 0, 0]),
    sphere(0xff6600, [0.06, 0.52, 0.3], 0.03, undefined, undefined, true),
    sphere(0xff6600, [-0.06, 0.52, 0.3], 0.03, undefined, undefined, true),
    // twin scythes
    cone(C_BONE, [0.28, 0.4, 0.1], 0.06, 0.55, [0.3, 0, -0.5]),
    cone(C_BONE, [-0.28, 0.4, 0.1], 0.06, 0.55, [0.3, 0, 0.5]),
    // coiled lower body
    sphere(c, [0, 0.15, -0.15], 0.22, [1.2, 0.7, 1]),
  ],
  baneling: (_d, c) => [
    sphere(c, [0, 0.1, 0], 0.3, [1, 0.85, 1]),
    sphere(0x88cc00, [0, 0.3, 0], 0.12, undefined, undefined, true),
    sphere(0x88cc00, [0.18, 0.15, 0.1], 0.08, undefined, undefined, true),
    sphere(0x88cc00, [-0.18, 0.15, 0.1], 0.08, undefined, undefined, true),
    sphere(0x88cc00, [0, 0.15, -0.2], 0.08, undefined, undefined, true),
    box(C_BONE, [0.12, -0.05, 0.1], [0.05, 0.1, 0.05], [0.3, 0, 0]),
    box(C_BONE, [-0.12, -0.05, 0.1], [0.05, 0.1, 0.05], [0.3, 0, 0]),
  ],
  ravager: (_d, c) => [
    box(c, [0, 0.2, 0], [0.34, 0.3, 0.55], [0.1, 0, 0]),
    box(C_CARAPACE, [0, 0.4, 0], [0.4, 0.12, 0.4], [0.15, 0, 0]),
    cone(C_BONE, [0, 0.55, -0.1], 0.1, 0.45, [-0.4, 0, 0]),
    cone(C_BONE, [0.15, 0.5, -0.05], 0.06, 0.3, [-0.4, 0, -0.3]),
    cone(C_BONE, [-0.15, 0.5, -0.05], 0.06, 0.3, [-0.4, 0, 0.3]),
    box(C_CARAPACE, [0, 0.18, 0.35], [0.22, 0.16, 0.22], [-0.2, 0, 0]),
    sphere(0xaa3300, [0, 0.22, 0.45], 0.06, undefined, undefined, true),
    box(C_CARAPACE, [0.25, 0.18, 0.05], [0.16, 0.08, 0.08], [0, 0.3, 0.4]),
    box(C_CARAPACE, [-0.25, 0.18, 0.05], [0.16, 0.08, 0.08], [0, -0.3, 0.4]),
    box(C_CARAPACE, [0.25, 0.18, -0.2], [0.16, 0.08, 0.08], [0, -0.3, 0.4]),
    box(C_CARAPACE, [-0.25, 0.18, -0.2], [0.16, 0.08, 0.08], [0, 0.3, 0.4]),
  ],
  mutalisk: (_d, c) => [
    sphere(c, [0, 0, 0], 0.28, [0.9, 0.7, 1.3]),
    cone(c, [0, 0.05, 0.3], 0.1, 0.3, [Math.PI / 2, 0, 0]),
    // membranous wings
    box(C_CARAPACE, [0.4, 0.05, -0.05], [0.55, 0.03, 0.4], [0, 0, 0.3]),
    box(C_CARAPACE, [-0.4, 0.05, -0.05], [0.55, 0.03, 0.4], [0, 0, -0.3]),
    cone(C_BONE, [0.65, 0.12, -0.1], 0.04, 0.3, [0, 0, 1.0]),
    cone(C_BONE, [-0.65, 0.12, -0.1], 0.04, 0.3, [0, 0, -1.0]),
    sphere(0xff6600, [0, 0.05, 0.25], 0.05, undefined, undefined, true),
    cone(C_CARAPACE, [0, 0, -0.35], 0.08, 0.3, [-Math.PI / 2, 0, 0]),
  ],
  corruptor: (_d, c) => [
    sphere(c, [0, 0, 0], 0.3, [1, 0.8, 1.1]),
    cone(C_CARAPACE, [0, 0.25, 0], 0.18, 0.3),
    box(C_CARAPACE, [0.35, 0, 0], [0.5, 0.04, 0.45], [0, 0, 0.2]),
    box(C_CARAPACE, [-0.35, 0, 0], [0.5, 0.04, 0.45], [0, 0, -0.2]),
    sphere(0x66ff44, [0, -0.05, 0.25], 0.08, undefined, undefined, true),
    cone(C_BONE, [0, -0.1, 0.35], 0.06, 0.3, [Math.PI / 2, 0, 0]),
  ],
  swarm_guard: (_d, c) => [
    sphere(c, [0, 0.1, 0], 0.5, [1.1, 0.9, 1.2]),
    box(C_CARAPACE, [0, 0.45, 0], [0.5, 0.2, 0.6]),
    cone(C_BONE, [0, 0.6, 0.1], 0.1, 0.4, [-0.3, 0, 0]),
    cone(C_BONE, [0.2, 0.55, 0], 0.08, 0.35, [-0.3, 0, -0.3]),
    cone(C_BONE, [-0.2, 0.55, 0], 0.08, 0.35, [-0.3, 0, 0.3]),
    sphere(0xaa3300, [0, 0.0, 0.4], 0.1, undefined, undefined, true),
  ],
  ultralisk: (_d, c) => [
    box(c, [0, 0.4, 0], [0.7, 0.55, 1.0]),
    box(C_CARAPACE, [0, 0.75, 0], [0.85, 0.25, 1.0]),
    cone(C_BONE, [0.25, 0.9, 0], 0.1, 0.5, [-0.3, 0, -0.2]),
    cone(C_BONE, [-0.25, 0.9, 0], 0.1, 0.5, [-0.3, 0, 0.2]),
    box(C_CARAPACE, [0, 0.35, 0.55], [0.4, 0.35, 0.4]),
    cone(C_BONE, [0.45, 0.45, 0.5], 0.1, 0.8, [1.2, 0, -0.3]),
    cone(C_BONE, [-0.45, 0.45, 0.5], 0.1, 0.8, [1.2, 0, 0.3]),
    cone(C_BONE, [0.2, 0.45, 0.6], 0.08, 0.7, [1.3, 0, -0.2]),
    cone(C_BONE, [-0.2, 0.45, 0.6], 0.08, 0.7, [1.3, 0, 0.2]),
    box(c, [0.3, 0.0, 0.2], [0.18, 0.4, 0.18]),
    box(c, [-0.3, 0.0, 0.2], [0.18, 0.4, 0.18]),
    box(c, [0.3, 0.0, -0.3], [0.18, 0.4, 0.18]),
    box(c, [-0.3, 0.0, -0.3], [0.18, 0.4, 0.18]),
  ],

  // ── Protoss ──────────────────────────────────────────────────────────────
  probe: (_d, c) => [
    sphere(c, [0, 0.05, 0], 0.22),
    sphere(C_BLUEGLOW, [0, -0.1, 0.2], 0.06, undefined, undefined, true),
    sphere(C_BLUEGLOW, [0, 0.2, 0], 0.04, undefined, undefined, true),
  ],
  zealot: (_d, c) => [
    box(c, [0, 0, 0], [0.5, 0.6, 0.35]),
    sphere(c, [0, 0.42, 0], 0.18),
    cone(C_GOLD, [0.15, 0.6, 0], 0.04, 0.25),
    cone(C_GOLD, [-0.15, 0.6, 0], 0.04, 0.25),
    box(C_BLUEGLOW, [0.3, 0.1, 0.2], [0.04, 0.04, 0.35], undefined, true),
    box(C_BLUEGLOW, [-0.3, 0.1, 0.2], [0.04, 0.04, 0.35], undefined, true),
    box(c, [-0.12, -0.45, 0], [0.12, 0.35, 0.12]),
    box(c, [0.12, -0.45, 0], [0.12, 0.35, 0.12]),
  ],
  adept: (_d, c) => [
    box(c, [0, 0, 0], [0.4, 0.5, 0.3]),
    sphere(c, [0, 0.38, 0], 0.15),
    sphere(0x44ccff, [0, 0.42, 0.12], 0.05, undefined, undefined, true),
    box(C_GOLD, [0.25, 0.05, 0.2], [0.08, 0.08, 0.3]),
    cone(0x44ccff, [0.25, 0.05, 0.4], 0.06, 0.15, undefined, true),
    box(c, [-0.25, -0.05, 0], [0.08, 0.3, 0.08]),
    box(C_GOLD, [0.25, 0.2, 0], [0.15, 0.08, 0.15]),
    box(C_GOLD, [-0.25, 0.2, 0], [0.15, 0.08, 0.15]),
    box(c, [-0.1, -0.42, 0], [0.1, 0.35, 0.1]),
    box(c, [0.1, -0.42, 0], [0.1, 0.35, 0.1]),
  ],
  dragoon: (_d, c) => [
    sphere(c, [0, 0.2, 0], 0.35),
    sphere(C_BLUEGLOW, [0, 0.2, 0.3], 0.15, undefined, undefined, true),
    cyl(C_GRAY, [0.3, -0.2, 0.3], 0.06, 0.6, [0.2, 0, 0.2]),
    cyl(C_GRAY, [-0.3, -0.2, 0.3], 0.06, 0.6, [0.2, 0, -0.2]),
    cyl(C_GRAY, [0.3, -0.2, -0.3], 0.06, 0.6, [-0.2, 0, 0.2]),
    cyl(C_GRAY, [-0.3, -0.2, -0.3], 0.06, 0.6, [-0.2, 0, -0.2]),
    cyl(C_GRAY, [0, 0.1, 0.5], 0.05, 0.3, [Math.PI / 2, 0, 0]),
  ],
  stalker: (_d, c) => [
    box(c, [0, 0.3, 0], [0.4, 0.35, 0.45]),
    box(C_GOLD, [0, 0.5, 0], [0.45, 0.1, 0.5]),
    cyl(C_GRAY, [0, 0.25, 0.4], 0.04, 0.4, [Math.PI / 2, 0, 0]),
    sphere(C_BLUEGLOW, [0, 0.25, 0.6], 0.06, undefined, undefined, true),
    cyl(C_GRAY, [0.3, 0.1, 0.2], 0.04, 0.35, [0.15, 0, 0.3]),
    cyl(C_GRAY, [0.39, -0.15, 0.26], 0.03, 0.3),
    cyl(C_GRAY, [-0.3, 0.1, 0.2], 0.04, 0.35, [0.15, 0, -0.3]),
    cyl(C_GRAY, [-0.39, -0.15, 0.26], 0.03, 0.3),
    cyl(C_GRAY, [0.3, 0.1, -0.2], 0.04, 0.35, [-0.15, 0, 0.3]),
    cyl(C_GRAY, [0.39, -0.15, -0.26], 0.03, 0.3),
    cyl(C_GRAY, [-0.3, 0.1, -0.2], 0.04, 0.35, [-0.15, 0, -0.3]),
    cyl(C_GRAY, [-0.39, -0.15, -0.26], 0.03, 0.3),
  ],
  immortal: (_d, c) => [
    box(c, [0, 0.15, 0], [0.7, 0.4, 0.6]),
    box(C_GOLD, [0, 0.4, 0], [0.75, 0.15, 0.65]),
    cyl(C_GRAY, [0.35, 0.2, 0.35], 0.06, 0.5, [Math.PI / 2, 0, 0]),
    cyl(C_GRAY, [-0.35, 0.2, 0.35], 0.06, 0.5, [Math.PI / 2, 0, 0]),
    sphere(C_BLUEGLOW, [0.35, 0.2, 0.6], 0.05, undefined, undefined, true),
    sphere(C_BLUEGLOW, [-0.35, 0.2, 0.6], 0.05, undefined, undefined, true),
    box(C_GRAY, [0.2, -0.15, 0], [0.15, 0.35, 0.15]),
    box(C_GRAY, [-0.2, -0.15, 0], [0.15, 0.35, 0.15]),
  ],
  colossus: (_d, c) => [
    box(c, [0, 0.9, 0], [0.45, 0.25, 0.6]),
    box(C_GOLD, [0, 1.05, 0], [0.5, 0.08, 0.65]),
    box(0xff4422, [0.28, 0.8, 0.1], [0.05, 0.15, 0.3], undefined, true),
    box(0xff4422, [-0.28, 0.8, 0.1], [0.05, 0.15, 0.3], undefined, true),
    cyl(C_GRAY, [0.3, 0.55, 0.2], 0.04, 0.5),
    cyl(C_GRAY, [0.375, 0.1, 0.24], 0.03, 0.5),
    box(C_GOLD, [0.375, -0.15, 0.24], [0.08, 0.04, 0.12]),
    cyl(C_GRAY, [-0.3, 0.55, 0.2], 0.04, 0.5),
    cyl(C_GRAY, [-0.375, 0.1, 0.24], 0.03, 0.5),
    box(C_GOLD, [-0.375, -0.15, 0.24], [0.08, 0.04, 0.12]),
    cyl(C_GRAY, [0.3, 0.55, -0.2], 0.04, 0.5),
    cyl(C_GRAY, [0.375, 0.1, -0.24], 0.03, 0.5),
    cyl(C_GRAY, [-0.3, 0.55, -0.2], 0.04, 0.5),
    cyl(C_GRAY, [-0.375, 0.1, -0.24], 0.03, 0.5),
  ],
  phoenix: (_d, c) => [
    sphere(c, [0, 0, 0], 0.2, [0.7, 0.4, 1.3]),
    sphere(C_BLUEGLOW, [0, 0.05, 0.2], 0.1, undefined, undefined, true),
    box(c, [0.35, 0, -0.1], [0.55, 0.03, 0.3]),
    box(c, [-0.35, 0, -0.1], [0.55, 0.03, 0.3]),
    cone(C_GOLD, [0, -0.05, -0.3], 0.06, 0.2, [-Math.PI / 2, 0, 0]),
  ],
  void_ray: (_d, c) => [
    box(c, [0, 0, 0], [0.3, 0.3, 1.0]),
    cone(c, [0, 0, 0.6], 0.18, 0.5, [Math.PI / 2, 0, 0]),
    box(C_GOLD, [0.25, 0, -0.1], [0.08, 0.5, 0.4], [0, 0, 0.3]),
    box(C_GOLD, [-0.25, 0, -0.1], [0.08, 0.5, 0.4], [0, 0, -0.3]),
    sphere(C_BLUEGLOW, [0, 0, 0.85], 0.08, undefined, undefined, true),
    cone(C_GOLD, [0, 0.25, -0.2], 0.06, 0.4, [0.2, 0, 0]),
  ],
  dark_templar: (_d, _c) => {
    const dark = 0x1a1024;
    return [
      box(dark, [0, 0, 0], [0.4, 0.55, 0.3]),
      sphere(dark, [0, 0.4, 0], 0.16),
      box(C_GOLD, [0, 0.55, 0], [0.06, 0.3, 0.06], [0, 0, 0.2]),
      box(0x7700cc, [0.32, 0.1, 0.25], [0.04, 0.04, 0.45], [0, 0.2, 0], true),
      box(0x7700cc, [-0.32, 0.1, 0.25], [0.04, 0.04, 0.45], [0, -0.2, 0], true),
      box(dark, [-0.1, -0.42, 0], [0.1, 0.32, 0.1]),
      box(dark, [0.1, -0.42, 0], [0.1, 0.32, 0.1]),
    ];
  },
  sentry: (_d, c) => [
    sphere(c, [0, 0.1, 0], 0.25),
    cone(C_GOLD, [0, 0.4, 0], 0.12, 0.25),
    sphere(C_BLUEGLOW, [0, 0.1, 0.22], 0.06, undefined, undefined, true),
    sphere(C_BLUEGLOW, [0, -0.15, 0], 0.1, undefined, undefined, true),
    box(C_GOLD, [0.2, 0.1, 0], [0.06, 0.2, 0.06], [0, 0, -0.3]),
    box(C_GOLD, [-0.2, 0.1, 0], [0.06, 0.2, 0.06], [0, 0, 0.3]),
  ],
};

// =============================================================================
// Fallback: recognizable silhouette by category / size / race
// =============================================================================
// Used for units without a hand-ported part list (most buildings + special
// units). Keeps a clear body + race-flavored accent so every unit still renders
// as a distinct, readable shape rather than a bare cube.

function fallbackParts(def: UnitDef, color: number): Part[] {
  const parts: Part[] = [];
  const sizeK = def.unitSize === 'large' ? 1.0 : def.unitSize === 'medium' ? 0.7 : 0.5;

  if (def.category === 'building') {
    // Buildings: chunky base + a race-distinct topper.
    parts.push(box(color, [0, 0.25, 0], [1.0, 0.5, 1.0]));
    parts.push(box(C_GRAY, [0, 0.55, 0], [0.7, 0.2, 0.7]));
    if (def.race === 'protoss') {
      parts.push(cone(C_GOLD, [0, 0.85, 0], 0.25, 0.5));
      parts.push(sphere(C_BLUEGLOW, [0, 0.95, 0], 0.1, undefined, undefined, true));
    } else if (def.race === 'zerg') {
      parts.push(sphere(C_CARAPACE, [0, 0.7, 0], 0.4, [1, 0.7, 1]));
      parts.push(cone(C_BONE, [0, 1.0, 0], 0.1, 0.4));
    } else {
      parts.push(box(0xffaa00, [0, 0.75, 0], [0.3, 0.15, 0.3], undefined, true));
      parts.push(cyl(C_GRAY, [0.35, 0.6, 0.35], 0.06, 0.5));
    }
    return parts;
  }

  // Mobile units: body + head + race accent + (ground) legs.
  if (def.race === 'zerg') {
    parts.push(sphere(color, [0, 0.1, 0], 0.35 * sizeK, [1, 0.8, 1.2]));
    parts.push(box(C_CARAPACE, [0, 0.35 * sizeK, 0], [0.4 * sizeK, 0.12, 0.4 * sizeK]));
    parts.push(cone(C_BONE, [0, 0.5 * sizeK, -0.05], 0.06, 0.3 * sizeK, [-0.4, 0, 0]));
  } else if (def.race === 'protoss') {
    parts.push(box(color, [0, 0, 0], [0.45 * sizeK, 0.55 * sizeK, 0.35 * sizeK]));
    parts.push(sphere(color, [0, 0.4 * sizeK, 0], 0.16 * sizeK));
    parts.push(cone(C_GOLD, [0, 0.6 * sizeK, 0], 0.04, 0.25 * sizeK));
    parts.push(sphere(C_BLUEGLOW, [0, 0.4 * sizeK, 0.15], 0.05, undefined, undefined, true));
  } else {
    parts.push(box(color, [0, 0, 0], [0.45 * sizeK, 0.55 * sizeK, 0.35 * sizeK]));
    parts.push(sphere(color, [0, 0.4 * sizeK, 0], 0.16 * sizeK));
    parts.push(sphere(C_BLUEGLOW, [0, 0.4 * sizeK, 0.15], 0.08, undefined, undefined, true));
  }
  if (def.isGround) {
    parts.push(box(color, [-0.12 * sizeK, -0.4 * sizeK, 0], [0.12 * sizeK, 0.3 * sizeK, 0.12 * sizeK]));
    parts.push(box(color, [0.12 * sizeK, -0.4 * sizeK, 0], [0.12 * sizeK, 0.3 * sizeK, 0.12 * sizeK]));
  }
  return parts;
}

/** typeIds with a hand-ported faithful model (the rest use fallbackParts). */
export const FAITHFUL_MODEL_IDS = Object.keys(UNIT_PARTS);
