// Default game template -- a small lowpoly "vignette" scene + a movable character.
//
// The STATIC scene (ground, sun, props, the character's INITIAL position) is an
// engine-native scene ASSET: `assets/scene.pack.json` (one `kind:'scene'` asset +
// N `kind:'material'` siblings, GUID refs), discovered by GUID via
// `forge.json.defaultScene`. main.ts loads it the SAME canonical way every other
// app does (apps/hello/room, apps/collectathon) -- `loadByGuid<SceneAsset>` ->
// `allocSharedRef` -> `assets.instantiate`. No bespoke pack preprocessing: the
// scene is authored in the CURRENT schema (`entities`, `MeshRenderer.materials`,
// dense localIds), so instantiate resolves refs[]->GUID->handle and builds the
// localId->Entity table itself. What you arrange in ✎ Edit is exactly what loads
// here in ▶ Play. This file adds only the DYNAMIC layer: the camera, WASD/arrow
// movement on the "Player" entity, and the HDR environment.
//
// One non-builtin asset still needs a runtime catalog before the load: the
// procedural cylinder mesh (TreeTrunk). Cube/sphere are engine builtins; the
// cylinder is generated by createCylinderGeometry, so we catalog it under its
// GUID first and the scene's recursive ref-load hits cache.
//
// No `@forgeax/scene` dependency: the pack is a plain engine pack, so the template
// stays self-contained inside the engine workspace.

import {
  Transform, Camera, perspective, quat, Materials, MeshFilter, MeshRenderer,
  SceneInstance,
  Skylight, SkyboxBackground, TONEMAP_REINHARD_EXTENDED,
  BLOOM_ENABLED, ANTIALIAS_FXAA, PointLight,
  type MaterialAsset, type Handle,
} from '@forgeax/engine-runtime';
import { HANDLE_CUBE, HANDLE_SPHERE } from '@forgeax/engine-assets-runtime';
import { pick } from '@forgeax/engine-picking';
import { createCylinderGeometry, createSphereGeometry } from '@forgeax/engine-geometry';

type MatHandle = Handle<'MaterialAsset', 'shared'>;
import { Collider, ColliderShapeValue, RigidBody, RigidBodyTypeValue } from '@forgeax/engine-physics';
import { AssetGuid } from '@forgeax/engine-pack/guid';
import { type EntityHandle, type World } from '@forgeax/engine-ecs';
import type { BootstrapContext } from '@forgeax/engine-app';
import type { SceneAsset, EquirectAsset } from '@forgeax/engine-types';
import { installHud, type ViewMode } from './src/hud';

/** Narrowed context for helper functions consuming world + optional assets/app. */
type Ctx = { world: World; assets?: import('@forgeax/engine-assets-runtime').AssetRegistry; app?: import('@forgeax/engine-app').App };

// sky.hdr lives in the forgeax-engine-assets submodule (demo-assets/template-
// game-default/sky.hdr + matching *.meta.json sidecar). pluginPack scans that
// directory and surfaces it through /pack-index.json -> loadByGuid<TextureAsset>
// -> renderer.store.uploadCubemapFromEquirect, the SAME native path the IBL
// learn-render demos use. Engine repo carries zero binaries.
const SKY_HDR_GUID = '81eec382-392f-5a93-8998-0ecf11ef7990';

// The scene's GUID (assets/scene.pack.json assets[0].guid; also forge.json
// defaultScene). loadByGuid<SceneAsset>(this) pulls the scene AND recursively
// its refs[] (the material siblings) from the pluginPack pack-index.
const SCENE_GUID = '1373372f-03e1-4abf-bd16-63ebf4d79523';

// Studio's cylinder mesh GUID (not an engine builtin -- cube/sphere are; the
// cylinder is procedural, createCylinderGeometry). The scene's refs[] points at
// it, so we catalog the geometry under this GUID BEFORE loadByGuid -- then the
// scene's recursive ref-load hits the catalog fast-path and instantiate's
// GUID->Handle resolve finds it. (Materials need no such step: they are sibling
// pack assets the pluginPack index already carries.)
const CYLINDER_GUID = 'c1111111-0000-5000-8000-000000000001';

// Defensive back-compat for an ✎ Edit round-trip: the editor re-saves Studio
// metadata `Collider` (its string `shape` name-collides with the numeric-enum
// physics Collider, and attachScenePhysics adds its own engine collider anyway).
// The SHIPPED pack is already clean (no Collider, `materials` array, dense
// localIds), but if a user edits + saves, strip Collider on load.
const STRIP_COMPONENTS = new Set(['Collider']);

interface PackNode { localId: number; components: Record<string, Record<string, unknown>> }

// Environment lighting. ALWAYS spawn a solid-color Skylight first: the forgeax
// PBR shader computes ambient=0 without a Skylight, so a lone DirectionalLight
// leaves every shaded face black. A cubemap-less Skylight binds the engine's
// 1x1 white irradiance cube -- ambient is live on the FIRST frame with zero
// async GPU work, and it renders on WebKit/WKWebView (the Tauri desktop app)
// whose WebGPU lacks the rgba16float render-attachment the IBL precompute needs.
// Then, on Chromium/Dawn only, upgrade that Skylight to full image-based
// lighting from sky.hdr + add the visible SkyboxBackground.
async function installHdrSky(ctx: Ctx): Promise<void> {
  const { world, assets } = ctx;
  // ALWAYS spawn a solid-color Skylight first: ambient is live on frame 1 with
  // zero async GPU work (and it renders on WebKit/WKWebView whose WebGPU lacks
  // the rgba16float render-attachment the IBL precompute needs).
  const skylight = world.spawn(
    { component: Skylight, data: { color: [0.9, 0.95, 1.0], intensity: 0.35 } },
  ).unwrap() as EntityHandle;
  if (!assets) return;

  // DECLARATIVE equirect: attach the EquirectAsset handle and let the engine
  // lazy-project it to a cubemap + IBL (caps-gated internally — no UA guard, no
  // private upload API). Then spawn the visible SkyboxBackground with the same
  // handle (mode defaults to cubemap).
  const guidRes = AssetGuid.parse(SKY_HDR_GUID);
  if (!guidRes.ok) {
    console.warn(`[game] sky GUID parse failed: ${guidRes.error.code}`);
    return;
  }
  const podRes = await assets.loadByGuid<EquirectAsset>(guidRes.value);
  if (!podRes.ok) {
    console.warn(`[game] sky.hdr loadByGuid failed: ${podRes.error.code}`);
    return;
  }
  const equirect = world.allocSharedRef<'EquirectAsset', EquirectAsset>('EquirectAsset', podRes.value);
  // Upgrade the existing Skylight to image-based lighting (neutral tint lets the
  // HDR drive the color).
  world.set(skylight, Skylight, { equirect, color: [1, 1, 1], intensity: 0.2 });
  world.spawn({ component: SkyboxBackground, data: { equirect } });
}

// Load the authored scene the canonical way -- loadByGuid<SceneAsset> ->
// allocSharedRef -> assets.instantiate -- and return the localId->Entity mapping
// (so the caller can find the Player) + the entity nodes (for per-node physics /
// player wiring). Returns null on any failure (caller falls back to a minimal
// scene). No bespoke pack parsing: the scene is authored in the current schema
// and instantiate resolves refs[]->GUID->handle + builds the mapping itself.
async function loadScene(
  ctx: Ctx,
): Promise<{ mapping: ReadonlyMap<number, EntityHandle>; nodes: PackNode[] } | null> {
  const { world, assets } = ctx;
  if (!assets) return null;

  // Pre-catalog the procedural cylinder mesh (TreeTrunk) under its GUID so the
  // scene's recursive ref-load hits the catalog fast-path. Cube/sphere are engine
  // builtins (auto-catalogued); materials are sibling pack assets the pluginPack
  // index already carries -- only the cylinder is generated at runtime.
  const cylG = AssetGuid.parse(CYLINDER_GUID);
  const cylGeo = createCylinderGeometry(0.5, 0.5, 1, 18);
  if (cylG.ok && cylGeo.ok) assets.catalog(cylG.value, cylGeo.value);

  const sceneGuid = AssetGuid.parse(SCENE_GUID);
  if (!sceneGuid.ok) return null;

  // loadByGuid pulls the scene AND recursively its refs[] (material siblings)
  // from the pluginPack pack-index; the returned payload (D-17) already has each
  // handle field resolved from a refs[] index to its GUID string.
  const loadRes = await assets.loadByGuid<SceneAsset>(sceneGuid.value);
  if (!loadRes.ok) { console.error('[game] scene loadByGuid failed:', loadRes.error); return null; }

  // Defensive normalisation for an ✎ Edit round-trip (the SHIPPED pack is already
  // clean, so this is a no-op on it): drop the editor's Studio-only `Collider`
  // (its string `shape` collides with the numeric-enum physics Collider, and
  // attachScenePhysics adds its own engine collider), and lift any legacy
  // singular `MeshRenderer.material` into the `materials` array the schema wants.
  const loadedEntities = (loadRes.value.entities ?? []) as unknown as PackNode[];
  const normalized = {
    kind: 'scene' as const,
    entities: loadedEntities.map((n) => {
      const components: Record<string, Record<string, unknown>> = {};
      for (const [name, data] of Object.entries(n.components)) {
        if (STRIP_COMPONENTS.has(name)) continue;
        if (name === 'MeshRenderer' && 'material' in data && !('materials' in data)) {
          const rest: Record<string, unknown> = { ...data };
          const single = rest.material;
          delete rest.material;
          components[name] = { ...rest, materials: single == null ? [] : [single] };
        } else {
          components[name] = data;
        }
      }
      return { localId: n.localId as unknown as number, components };
    }),
  };

  // assets.instantiate returns the synthetic root Entity directly (engine #330);
  // it wires the World-level scene resolver, resolves GUID->handle, spawns every
  // node, and stamps the `SceneInstance` component whose `mapping` Uint32Array is
  // indexed by authored localId. (engine sizes mapping to maxLocalId+1, so sparse
  // localIds from an editor delete no longer drop entities -- the old compaction
  // workaround is gone.)
  const sceneHandle = world.allocSharedRef('SceneAsset', normalized as unknown as SceneAsset);
  const instRes = assets.instantiate<SceneAsset>(sceneHandle, world);
  if (!instRes.ok) { console.error('[game] scene instantiate failed:', (instRes.error as { code?: string })?.code); return null; }
  const root = instRes.value;
  const sceneInst = world.get(root, SceneInstance);
  if (!sceneInst.ok) { console.error('[game] SceneInstance lookup failed:', sceneInst.error); return null; }
  const mappingArr = sceneInst.value.mapping as unknown as ArrayLike<number>;
  const mapping = new Map<number, EntityHandle>();
  for (const n of normalized.entities) {
    const localId = n.localId as unknown as number;
    const e = mappingArr[localId];
    if (e !== undefined) mapping.set(localId, e as EntityHandle);
  }
  return { mapping, nodes: normalized.entities as unknown as PackNode[] };
}

// Minimal fallback scene (ground + cube + sun) so Play still runs if the pack is
// missing/unreadable. The editor authors the real one.
function spawnFallbackScene(ctx: Ctx): void {
  const { world, assets } = ctx;
  const ground = world.allocSharedRef<'MaterialAsset', MaterialAsset>('MaterialAsset', Materials.standard({ baseColor: [0.48, 0.62, 0.35, 1], roughness: 0.95, metallic: 0 }));
  world.spawn(
    { component: Transform, data: { pos: [0, -0.1, 0], scale: [24, 0.2, 24] } },
    { component: MeshFilter, data: { assetHandle: HANDLE_CUBE } },
    { component: MeshRenderer, data: { materials: [ground] } },
  );
}

// A THICK invisible static floor whose TOP sits at y=0 (the visual ground's top).
// Dynamic props rest + collide against this, not the thin 0.2-tall visual ground —
// so a hard knock can't push them partway THROUGH a thin slab and leave them sunk.
function spawnGroundCollider(ctx: Ctx): void {
  ctx.world.spawn(
    { component: Transform, data: { pos: [0, -5, 0] } },
    { component: RigidBody, data: { type: RigidBodyTypeValue.static } },
    { component: Collider, data: { shape: ColliderShapeValue.cuboid, halfExtents: [60, 5, 60], friction: 0.9, restitution: 0 } },
  );
}

// The player root's rest height (matches the authored "Player" root in the pack):
// its kinematic capsule (radius 0.3 + halfHeight 0.4) is centered here.
const PLAYER_Y = 0.75;

// Attach engine physics (RigidBody + Collider) to the instantiated scene, by entity
// Name. The pack's authored `Collider` is stripped on load (Studio metadata, a
// different schema); engine colliders are sized here from each entity's mesh +
// Transform.scale. Collider dimensions are ABSOLUTE (Rapier doesn't scale colliders
// by Transform), so halfExtents = unit-mesh-extent(1)·scale·0.5, sphere radius =
// scale·0.5 (unit sphere r=0.5).
//   Ground                        → static box (immovable floor)
//   RedBox / BlueBall / YellowPillar → dynamic (fall, get shoved + knocked flying)
//   TreeTrunk / TreeCanopy        → Collider ONLY = static obstacle, never simulated
//                                   (树有碰撞体、无物理 — dynamic props bounce off it)
//   Player / Sun                  → skipped (Player becomes the kinematic box-man root)
function attachScenePhysics(
  ctx: Ctx,
  loaded: { mapping: ReadonlyMap<number, EntityHandle>; nodes: PackNode[] },
): {
  props: Array<{ e: EntityHandle; mat: MatHandle }>;
  walkBlockers: Array<{ cx: number; cz: number; r: number }>;
  targets: Array<{ e: EntityHandle; points: number }>;
} {
  const { world } = ctx;
  const props: Array<{ e: EntityHandle; mat: MatHandle }> = [];    // dynamic → hit-flash targets
  const targets: Array<{ e: EntityHandle; points: number }> = [];  // scorable props (entity → points)
  // XZ circles the kinematic player can't enter (the tree TRUNK). The player is
  // kinematic → rapier gives it no collision response vs static bodies, so we
  // block it manually. A single forward raycast missed the thin (0.4-wide) trunk
  // from off-center angles; an XZ push-out blocks from EVERY angle. Only obstacles
  // that sit on the ground (yMin < 0.8) are walk-blockers — an elevated obstacle
  // (the canopy, yMin 1.0) is foliage you walk UNDER, not into.
  const walkBlockers: Array<{ cx: number; cz: number; r: number }> = [];
  const addBlocker = (cx: number, cz: number, r: number, yMin: number) => {
    if (yMin < 0.8) walkBlockers.push({ cx, cz, r });
  };
  const matOf = (e: EntityHandle): MatHandle => {
    const mr = world.get(e, MeshRenderer);
    return (mr.ok ? mr.value.materials[0] : 0) as MatHandle;
  };
  for (const node of loaded.nodes) {
    const name = (node.components.Name as { value?: string } | undefined)?.value;
    const e = loaded.mapping.get(node.localId);
    if (e === undefined || !name) continue;
    const t = (node.components.Transform ?? {}) as Record<string, number[]>;
    // Collider sizing: the builtin CUBE is createBoxGeometry(1,1,1) → extent 1
    // (half 0.5), but the builtin SPHERE is createSphereGeometry(1,…) → radius 1.
    // So a cuboid half-extent is scale·0.5, while a sphere's radius is the FULL
    // scale (scale·1). Getting this wrong makes the collider half the visual size
    // → the mesh sinks into the floor and bodies interpenetrate before colliding.
    const hx = (t.scale?.[0] ?? 1) * 0.5, hy = (t.scale?.[1] ?? 1) * 0.5, hz = (t.scale?.[2] ?? 1) * 0.5;
    const sphereR = t.scale?.[0] ?? 1;
    const box = (restitution: number) =>
      world.addComponent(e, { component: Collider, data: { shape: ColliderShapeValue.cuboid, halfExtents: [hx, hy, hz], restitution, friction: 0.7 } });
    const sphere = (restitution: number) =>
      world.addComponent(e, { component: Collider, data: { shape: ColliderShapeValue.sphere, radius: sphereR, restitution, friction: 0.6 } });
    const dynamic = () =>
      world.addComponent(e, { component: RigidBody, data: { type: RigidBodyTypeValue.dynamic, mass: 1, linearDamping: 0.05, angularDamping: 0.1, ccdEnabled: true } });
    const staticBody = () =>
      world.addComponent(e, { component: RigidBody, data: { type: RigidBodyTypeValue.static } });
    switch (name) {
      // Ground gets NO collider here — a separate THICK floor (spawnGroundCollider)
      // handles collision. A thin 0.2-tall ground slab lets a hard knock push a
      // dynamic body partway THROUGH it (penetration that doesn't recover → the
      // prop rests sunk into the ground). A deep floor box can't be tunneled.
      case 'Ground': break;
      // Tree = STATIC body (immovable, never simulated — "no physics") so props
      // bounce off it. NOTE: this engine's physicsSyncBackend only registers
      // entities with the full (Transform, RigidBody, Collider) triplet, so a
      // Collider WITHOUT a RigidBody is silently ignored (no collision at all).
      // A static RigidBody is the right way to get an immovable obstacle.
      case 'TreeTrunk': staticBody(); box(0.2); addBlocker(t.pos?.[0] ?? 0, t.pos?.[2] ?? 0, Math.hypot(hx, hz), (t.pos?.[1] ?? 0) - hy); break;
      case 'TreeCanopy': staticBody(); sphere(0.2); addBlocker(t.pos?.[0] ?? 0, t.pos?.[2] ?? 0, sphereR, (t.pos?.[1] ?? 0) - sphereR); break;
      case 'RedBox': dynamic(); box(0.25); props.push({ e, mat: matOf(e) }); targets.push({ e, points: 10 }); break;
      case 'BlueBall': dynamic(); sphere(0.55); props.push({ e, mat: matOf(e) }); targets.push({ e, points: 15 }); break;
      case 'YellowPillar': dynamic(); box(0.2); props.push({ e, mat: matOf(e) }); targets.push({ e, points: 10 }); break;
      // showcase props — now AUTHORED in scene.pack.json (so ✎ Edit shows them
      // too); main.ts just gives them dynamics. "Crate*" = knockable pyramid,
      // "BouncyBall" = high-restitution bouncer.
      case 'BouncyBall': dynamic(); sphere(0.92); props.push({ e, mat: matOf(e) }); targets.push({ e, points: 25 }); break;
      default:
        if (name.startsWith('Crate')) { dynamic(); box(0.1); props.push({ e, mat: matOf(e) }); targets.push({ e, points: 5 }); }
        break;
    }
  }
  return { props, walkBlockers, targets };
}

// Wire up the low-poly box-man. Its cube parts ("PlayerTorso/Head/ArmL/ArmR/LegL/
// LegR") are authored in scene.pack.json as ChildOf children of the "Player" root
// with LOCAL coordinates — a single hierarchy representation that both ✎ Edit and
// ▶ Play consume verbatim (the editor viewport and Play run the same engine +
// propagateTransforms, so ChildOf resolves in both; scene-pack round-trips ChildOf
// losslessly). So the avatar already renders + moves as a unit; here we only make
// the root a kinematic body (driven by its Transform → shoves props). No runtime
// re-parenting: that split representation (flat pack + Play-time reparent) was a
// SSOT violation and the source of a stale-view bug (reading a Transform array view
// across the ChildOf archetype migration scrambled the parts).
function setupPlayerRoot(ctx: Ctx, root: EntityHandle): void {
  const { world } = ctx;
  world.addComponent(root, { component: RigidBody, data: { type: RigidBodyTypeValue.kinematic } });
  world.addComponent(root, { component: Collider, data: { shape: ColliderShapeValue.capsule, radius: 0.3, halfHeight: 0.4 } });
}

export async function bootstrap(world: World, ctx?: BootstrapContext) {
  const { registerUpdate } = ctx ?? {};

  const canvas = document.querySelector<HTMLCanvasElement>('#app')!;
  const dpr = window.devicePixelRatio || 1;
  canvas.width = Math.max(1, Math.floor(canvas.clientWidth * dpr));
  canvas.height = Math.max(1, Math.floor(canvas.clientHeight * dpr));
  const aspect = canvas.width / canvas.height || 1;

  // ── load the authored scene (the SAME native asset ✎ Edit writes) — the
  //    canonical loadByGuid<SceneAsset> -> instantiate path. ────────────────────
  let loaded: { mapping: ReadonlyMap<number, EntityHandle>; nodes: PackNode[] } | null = null;
  try {
    loaded = await loadScene({ world, assets: ctx?.assets });
  } catch (err) {
    console.warn('[game] scene asset unavailable:', err);
  }
  if (!loaded) spawnFallbackScene({ world });

  // Thick physics floor (top at y=0) so knocked props can't sink into the ground.
  spawnGroundCollider({ world });

  // HDR environment (skylight + skybox) -- same as ✎ Edit. tonemap (below) must be
  // active for the skybox pass; store lives on the app's renderer.
  void installHdrSky({ world, assets: ctx?.assets, app: ctx?.app });

  // ── physics: attach RigidBody/Collider to the scene + spawn showcase props,
  //    then make the Player a kinematic box-man root (▶ Play simulates; ✎ Edit
  //    never enables physics). ──────────────────────────────────────────────────
  let player: EntityHandle | undefined;
  let initX = 0, initZ = 0;
  // XZ circles the kinematic player is pushed out of (the tree trunk).
  const walkBlockers: Array<{ cx: number; cz: number; r: number }> = [];
  const flashables: Array<{ e: EntityHandle; mat: MatHandle }> = []; // hit-flash targets (dynamic props)
  const targets: Array<{ e: EntityHandle; points: number }> = [];    // scorable props (entity → points)
  if (loaded) {
    const phys = attachScenePhysics({ world }, loaded);
    walkBlockers.push(...phys.walkBlockers);
    flashables.push(...phys.props);
    targets.push(...phys.targets);
    const playerNode = loaded.nodes.find((n) => (n.components.Name as { value?: string } | undefined)?.value === 'Player');
    if (playerNode) {
      const t = (playerNode.components.Transform ?? {}) as Record<string, number[]>;
      initX = t.pos?.[0] ?? 0; initZ = t.pos?.[2] ?? 0;
      player = loaded.mapping.get(playerNode.localId);
      if (player !== undefined) setupPlayerRoot({ world }, player);
    }
  }
  const origMatOf = new Map<EntityHandle, MatHandle>(flashables.map((f) => [f.e, f.mat] as [EntityHandle, MatHandle]));

  // ── camera: TWO switchable view modes (top-down 2.5D ⇄ first-person) ─────────
  // Top-down = a high tilted follow cam; FPS = an eye-height cam driven by
  // pointer-lock mouse-look. An on-screen UI button (HUD, below) toggles them.
  // antialias: ANTIALIAS_FXAA = post-process anti-aliasing (learn-render §4).
  const TOP_DY = 13, TOP_DZ = 9;                 // top-down offset (steeper = more 2.5D)
  const CAM_FOLLOW = 8;                          // top-down follow stiffness
  const EYE = 0.55;                              // FPS eye height above the player root (≈ box-man head, y≈1.3)
  const topPitch = -Math.atan2(TOP_DY, TOP_DZ);  // top-down look-down pitch
  const topQ = quat.create();
  quat.fromAxisAngle(topQ, [1, 0, 0], topPitch);
  let camX = initX, camZ = initZ + TOP_DZ;
  const camera = world.spawn(
    { component: Transform, data: { pos: [camX, TOP_DY, camZ], quat: [topQ[0]!, topQ[1]!, topQ[2]!, topQ[3]!] } },
    // clearR/G/B = visible sky background. WebKit/WKWebView (the desktop app)
    // can't render the cubemap SkyboxBackground (needs rgba16float render targets
    // it lacks), so without this the background clears to black. The Camera clear
    // color needs no GPU feature; a daytime blue reads as sky. Linear/pre-tonemap.
    // On Chromium the cubemap skybox draws over it (harmless).
    { component: Camera, data: { ...perspective({ fov: Math.PI / 3, aspect, near: 0.1, far: 200 }), tonemap: TONEMAP_REINHARD_EXTENDED, bloom: BLOOM_ENABLED, antialias: ANTIALIAS_FXAA, clearColor: [0.4, 0.6, 1.0, 1] } },
  ).unwrap();

  // ── one warm accent point light (learn-render §2 multiple-lights; the scene
  //    already has the directional Sun + IBL skylight — keep ≤1 of each). ───────
  world.spawn(
    { component: Transform, data: { pos: [3, 5, 1] } },
    { component: PointLight, data: { color: [1, 0.72, 0.42], intensity: 40, range: 22 } },
  );

  // ── on-hit "+N" popup ────────────────────────────────────────────────────
  //   Score popups are a **DOM overlay**, NOT a world-space GlyphText entity.
  //
  //   Why: the engine's shadow caster pass (render-system-record.ts:2611-2630)
  //   projects every entity with a triangle-list/triangle-strip submesh into
  //   the directional shadow map — there is no per-material `castShadow:false`
  //   yet (design doc 2026-06-09 covers it; not yet landed). A world-space
  //   GlyphText popup at prop.y+0.8 with billboard-to-camera rotation lies
  //   near-horizontal in top-down view, and the sun-direction projection of
  //   that quad onto the ground produced a clearly visible circular shadow at
  //   the hit prop's feet (bug-20260610-glyph-mesh-cannot-opt-out-shadow-
  //   caster). DOM overlay sidesteps the shadow path entirely.
  //
  //   spawnPopup runs from the registerUpdate callback (after hit detection),
  //   projects (worldX, worldY, worldZ) to canvas-CSS-pixel screen coords
  //   inline using the camera's current Transform + a hardcoded perspective
  //   FOV (matches the Camera spawn above), and hands off to hud.floatScore
  //   which spawns a brief animated div.
  const targetPoints = new Map<EntityHandle, number>(targets.map((t) => [t.e, t.points] as [EntityHandle, number]));

  // Box-man body parts (PlayerTorso/Head/Arm*/Leg*): hidden in FPS so they don't
  // occlude the eye-level camera, shown in top-down. Toggled by scaling to 0 (safe
  // partial Transform set — no add/remove churn). Scales read AFTER setupPlayerRoot.
  const bodyParts: Array<{ e: EntityHandle; sx: number; sy: number; sz: number }> = [];
  if (loaded) {
    for (const n of loaded.nodes) {
      const nm = (n.components.Name as { value?: string } | undefined)?.value;
      if (nm && nm.startsWith('Player') && nm !== 'Player') {
        const pe = loaded.mapping.get(n.localId);
        if (pe === undefined) continue;
        const tr = world.get(pe, Transform);
        bodyParts.push({ e: pe, sx: tr.ok ? tr.value.scale[0]! : 1, sy: tr.ok ? tr.value.scale[1]! : 1, sz: tr.ok ? tr.value.scale[2]! : 1 });
      }
    }
  }
  const setPlayerVisible = (vis: boolean) => {
    for (const p of bodyParts) {
      world.set(p.e, Transform, vis ? { scale: [p.sx, p.sy, p.sz] } : { scale: [0, 0, 0] });
    }
  };

  // ── on-screen UI + view-mode state (DOM overlay; gameplay stays ECS) ─────────
  let mode: ViewMode = 'topdown';
  let score = 0;
  let locked = false;
  // Pointer-lock path. Two modes:
  //   - Web (Chrome/Edge): use the real Pointer Lock API (`requestPointerLock`).
  //   - Tauri WKWebView: WKWebView DENIES the web API for embedded content (see
  //     packages/interface/src-tauri/src/lib.rs:24-32), so we use the team's
  //     Tauri-native fallback: postMessage({type:'fx-pointer-capture', capture})
  //     to the parent, which invokes the `set_pointer_capture` Tauri command →
  //     `window.set_cursor_grab` (CGAssociateMouseAndMouseCursorPosition(false)
  //     on macOS) + `set_cursor_visible(false)`. Listener: PreviewMode.tsx:58-69.
  //
  // CRUCIAL: we do NOT opt into forge.json `pointerLock:true`. That flag makes
  // the Play host install its OWN canvas click handler that calls setCaptured(true)
  // on every click (host main.ts:179) — which posts fx-pointer-capture true and
  // locks the cursor in BOTH modes (the user-reported "top-down also locks"
  // bug). Without the flag the host noops `canvas.requestPointerLock` instance-
  // level, but we bypass that with the prototype method (`realRequestLock`), so
  // FPS lock still works on Web. Top-down has zero lock paths.
  const realRequestLock = HTMLElement.prototype.requestPointerLock;
  const postCapture = (capture: boolean) => {
    try { window.parent.postMessage({ type: 'fx-pointer-capture', capture }, '*'); } catch { /* not embedded */ }
  };
  // setMode is captured inside the toggle button click; declared above the HUD
  // so installHud's onToggle can call it.
  const setMode = (m: ViewMode) => {
    mode = m;
    hud.setMode(m);
    setPlayerVisible(m !== 'fps');
    canvas.style.cursor = m === 'fps' ? 'crosshair' : '';
    if (m !== 'fps' && locked) {
      // Leaving FPS — release whichever lock is engaged (web or Tauri-native).
      postCapture(false);
      try { document.exitPointerLock?.(); } catch { /* ignore */ }
      setLocked(false);
    }
    // Don't request lock from here: setMode is called from the toggle BUTTON's
    // click; Chromium rejects pointer-lock requests on a different element from
    // the gesture's target. The canvas mousedown below requests it instead
    // (same-element gesture; matches packages/games/fps).
  };
  // Host-controlled UI mount (■ Stop teardown): the HUD must attach to the host-
  // provided uiRoot (the disposable container the Play host removes WHOLE on Stop)
  // so no UI is stranded. Falls back to document.body only when the host omits it.
  const uiMount: HTMLElement = ctx?.uiRoot ?? document.body;
  const hud = installHud({ initialMode: 'topdown', onToggle: () => setMode(mode === 'fps' ? 'topdown' : 'fps'), mount: uiMount });

  // World-space → canvas-CSS-pixel projection for the DOM "+N" popup. Reads
  // the camera's CURRENT Transform (the registerUpdate callback that calls
  // spawnPopup runs AFTER the camera Transform write each frame, so values
  // are fresh). FOV / near match the Camera spawn above. Returns negative
  // coords for off-screen / behind-camera; floatScore tolerates that by just
  // rendering off-canvas (clipped). HUD sx/sy are in canvas-local CSS pixels;
  // since the HUD root is `position: fixed; inset: 0` matching the iframe
  // viewport that the canvas fills, canvas.clientWidth/Height is the right
  // basis without an additional canvas getBoundingClientRect() lookup.
  const FOV = Math.PI / 3;
  const spawnPopup = (text: string, wx: number, wy: number, wz: number): void => {
    const camTr = world.get(camera, Transform);
    if (!camTr.ok) return;
    const cpx = camTr.value.pos[0]!, cpy = camTr.value.pos[1]!, cpz = camTr.value.pos[2]!;
    // Inverse camera rotation = quaternion conjugate (negate xyz, keep w).
    const qx = -camTr.value.quat[0]!, qy = -camTr.value.quat[1]!, qz = -camTr.value.quat[2]!, qw = camTr.value.quat[3]!;
    const dx = wx - cpx, dy = wy - cpy, dz = wz - cpz;
    // Quat-vector rotation: t = 2 * (q.xyz × v); v' = v + q.w * t + q.xyz × t.
    const tx = 2 * (qy * dz - qz * dy);
    const ty = 2 * (qz * dx - qx * dz);
    const tz = 2 * (qx * dy - qy * dx);
    const lx = dx + qw * tx + (qy * tz - qz * ty);
    const ly = dy + qw * ty + (qz * tx - qx * tz);
    const lz = dz + qw * tz + (qx * ty - qy * tx);
    if (lz >= -0.05) return;   // behind / on top of camera near plane
    const cssW = canvas.clientWidth, cssH = canvas.clientHeight;
    if (cssW <= 0 || cssH <= 0) return;
    const f = 1 / Math.tan(FOV * 0.5);
    const ndcX = (lx * f) / (-lz * (cssW / cssH));
    const ndcY = (ly * f) / -lz;
    if (ndcX < -1.2 || ndcX > 1.2 || ndcY < -1.2 || ndcY > 1.2) return;
    const sx = (ndcX + 1) * 0.5 * cssW;
    const sy = (1 - ndcY) * 0.5 * cssH;
    hud.floatScore(text, sx, sy);
  };

  // Track lock state via BOTH web Pointer Lock events AND our manual flag (set
  // by the Tauri postCapture path, where pointerLockElement stays null).
  const setLocked = (v: boolean) => {
    locked = v;
    canvas.style.cursor = v ? 'none' : (mode === 'fps' ? 'crosshair' : '');
    hud.setLockStatus(v ? '🎮 已锁定 · 鼠标转视角 · ESC 释放' : '🖱️ 点击画面锁定鼠标');
  };
  document.addEventListener('pointerlockchange', () => setLocked(document.pointerLockElement === canvas));
  document.addEventListener('pointerlockerror', () => {
    // Web API rejected. ONLY fall back to Tauri-native cursor grab when in FPS:
    // engine-input's onCanvasClick (browser-backend.ts) auto-calls
    // canvas.requestPointerLock() on EVERY canvas click — in top-down mode that
    // fires pointerlockerror in WKWebView/CDP-driven Chrome, and an unconditional
    // fallback would lock the cursor in top-down too (the user-reported bug).
    if (mode !== 'fps') return;
    console.warn('[game] web pointer-lock denied — falling back to Tauri-native cursor grab via postMessage');
    postCapture(true);
    setLocked(true);
  });
  // Manual ESC handler — required for the Tauri path (no browser-native ESC release
  // since the web API was never engaged). Web path: ESC releases automatically
  // and pointerlockchange fires; this listener also fires but `setLocked(false)`
  // is idempotent. postCapture(false) tells Tauri to release the OS cursor grab.
  window.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && locked) {
      postCapture(false);
      try { document.exitPointerLock?.(); } catch { /* ignore */ }
      setLocked(false);
    }
  });

  // ── input: keyboard (WASD/Space/F) + mouse (FPS look; click = pick / shoot) ──
  const keys: Record<string, boolean> = {};
  window.addEventListener('keydown', (e) => {
    keys[e.code] = true;
    if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Space'].includes(e.code)) e.preventDefault();
  });
  window.addEventListener('keyup', (e) => { keys[e.code] = false; });

  // FPS mouse-look: STANDARD POINTER-LOCK pattern — click locks the cursor
  // (hidden), then mousemove movementX/Y rotates the view (infinite turn). ESC
  // releases. Arrow keys remain a keyboard fallback if lock can't be granted.
  const LOOK_SENS = 0.0022;
  let lookYaw = 0;     // 0 → forward (0,-1); forward = (-sin yaw, -cos yaw)
  let lookPitch = 0;
  let wantShoot = false;
  // Top-down click sets a one-shot world-XZ aim direction here; the fire block
  // consumes it (so a click-aim is preserved even if the player is moving and
  // the movement block overwrites faceX/faceZ on the same frame).
  let shotDir: { x: number; z: number } | null = null;
  const clampPitch = (p: number) => Math.max(-1.2, Math.min(1.2, p));
  window.addEventListener('mousemove', (e) => {
    if (mode !== 'fps' || !locked) return;          // ONLY look while locked → cursor never "flies"
    lookYaw -= e.movementX * LOOK_SENS;
    lookPitch = clampPitch(lookPitch - e.movementY * LOOK_SENS);
  });

  // Detect Tauri once (WKWebView denies the web Pointer Lock API for embedded
  // content; we use the native cursor-grab path via parent postMessage).
  const isTauri = !!(window as unknown as { __TAURI__?: unknown }).__TAURI__
               || !!(window as unknown as { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__;

  // FPS-only: mousedown grabs the pointer-lock (the canvas is the user-gesture
  // target). Top-down's click is handled in the click listener below.
  canvas.addEventListener('mousedown', () => {
    if (mode !== 'fps' || locked) return;
    if (isTauri) {
      // Tauri WKWebView: jump straight to the native cursor grab — web pointer-lock
      // would silently fail without firing pointerlockerror.
      postCapture(true);
      setLocked(true);
    } else {
      // Web browser: PROTOTYPE method bypass — the host noops `canvas.requestPointerLock`
      // instance-level for non-FPS games (and we deliberately don't opt-in via
      // forge.json to avoid the host's auto-capture-every-click handler). The
      // prototype method `realRequestLock.call(canvas)` is the real native call
      // and engages lock from this same-element user gesture.
      try { realRequestLock.call(canvas); } catch { /* error listener handles fallback */ }
    }
  });

  // Click handling, per mode:
  //   - FPS (locked):   click → shoot forward (look direction).
  //   - FPS (unlocked): click → no-op (mousedown above already requested lock).
  //   - Top-down:       click → AIM character toward the click point, then shoot.
  //                     pick() snaps onto an entity under the cursor (so shooting
  //                     a target is precise); on a miss the click direction is
  //                     projected from canvas-center into world XZ (canvas Y down
  //                     ↔ world +Z under the top-down tilt). The aim is stashed
  //                     in `shotDir` so a moving player still shoots toward the
  //                     click (the movement block doesn't override it for the
  //                     fire frame).
  canvas.addEventListener('click', (e) => {
    if (mode === 'fps') {
      if (locked) wantShoot = true;
      return;
    }
    const rect = canvas.getBoundingClientRect();
    const sx = (e.clientX - rect.left) * (canvas.width / Math.max(1, rect.width));
    const sy = (e.clientY - rect.top) * (canvas.height / Math.max(1, rect.height));
    let aimX: number, aimZ: number;
    const hit = pick(world, camera, sx, sy, canvas.width, canvas.height);
    if (hit) {
      const tr = world.get(hit.entity, Transform);
      if (tr.ok) { aimX = tr.value.pos[0]!; aimZ = tr.value.pos[2]!; }
      else { aimX = px + (sx - canvas.width / 2); aimZ = pz + (sy - canvas.height / 2); }
    } else {
      aimX = px + (sx - canvas.width / 2); aimZ = pz + (sy - canvas.height / 2);
    }
    const dx = aimX - px, dz = aimZ - pz;
    const len = Math.hypot(dx, dz);
    if (len > 1e-3) {
      const nx = dx / len, nz = dz / len;
      shotDir = { x: nx, z: nz };
      faceX = nx; faceZ = nz;       // visually face the shot direction
      wantShoot = true;
    }
  });

  // Bullet material — EMISSIVE so it glows and drives the Camera.bloom bright-pass
  // (HDR emissive > bloomThreshold 1.0 → blooms). Showcases the post-processing path.
  const bulletMat = world.allocSharedRef<'MaterialAsset', MaterialAsset>('MaterialAsset', Materials.standard({ baseColor: [1, 0.85, 0.3, 1], roughness: 0.4, metallic: 0, emissive: [1, 0.7, 0.15], emissiveIntensity: 5 }));
  // Bullet mesh — a 0.2-radius sphere baked AT the visual size (Transform.scale
  // stays 1). The default HANDLE_SPHERE is a UNIT sphere; using `scale 0.2` to
  // shrink it produced a large round ground shadow on every shot — a code path
  // somewhere along the shadow-caster pipeline reads the unit-mesh extent
  // before Transform.scale is folded in. Baking the geometry at the final
  // radius removes the scale dependency and the shadow now matches the bullet.
  const bulletMeshRes = createSphereGeometry(0.2, 12, 8);
  const bulletMesh = bulletMeshRes.ok ? world.allocSharedRef('MeshAsset', bulletMeshRes.value) : HANDLE_SPHERE;
  // Hit-flash material — a bright emissive white-yellow swapped onto a prop for a
  // few frames when a bullet strikes it (then restored to its base material).
  const flashMat = world.allocSharedRef<'MaterialAsset', MaterialAsset>('MaterialAsset', Materials.standard({ baseColor: [1, 1, 0.9, 1], roughness: 0.5, metallic: 0, emissive: [1, 1, 0.6], emissiveIntensity: 6 }));
  const flashUntil = new Map<EntityHandle, number>();    // entity → remaining flash seconds
  // squared hit radius for bullet→prop scoring. Aligned with the bullet's
  // 0.5-radius collider — proximity fires the same moment the physics contact
  // zone is entered (bullet_r 0.5 + avg prop_r 0.5 ≈ 1.0). Slight overshoot is
  // fine: per-bullet `hits` set prevents duplicate scoring during pass-through.
  const HIT2 = 1.1 * 1.1;

  // ── gameplay update (▶ Play only — ✎ Edit stays static) ─────────────────────
  const SPEED = 6;            // walk speed (units/s)
  const PLAYER_RADIUS = 0.3;  // = the kinematic capsule radius (setupPlayerRoot)
  const BOUND = 11;           // keep the character on the 24-wide ground slab
  const JUMP_V = 6.5;         // initial jump velocity
  const GRAV = 18;            // jump gravity (manual arc — the root is kinematic)
  const BULLET_SPEED = 24;    // bullet travel speed (units/s)
  const BULLET_LIFE = 1.5;    // bullet lifetime (s)
  const SHOOT_CD = 0.18;      // fire cooldown (s)

  let px = initX, pz = initZ;
  let faceX = 0, faceZ = -1;          // facing unit vector (default: into the scene)
  let jumpY = PLAYER_Y, vy = 0, grounded = true, prevSpace = false;
  let shootCd = 0;
  // Bullets fly THROUGH props rather than despawning on contact. Why: rapier's
  // kinematic-vs-dynamic push is velocity-driven (delta of setNextKinematicTranslation
  // per step → kinematic velocity → impulse to dynamic). Despawning on the hit
  // frame gives only ONE step of contact, which is (a) sometimes missed entirely
  // due to discrete-collision timing, and (b) only a small impulse → "random
  // knock" feel. Letting the bullet keep flying means ~3 physics steps of
  // contact while the bullet's collider is inside the prop's collider (step 0.4
  // / prop diameter ~1) → multiple push impulses → reliable knock-back. The
  // per-bullet `hits` set prevents double-scoring the same prop. Bullet despawns
  // on lifetime expiry (BULLET_LIFE) — no leftover ball-shadow because it never
  // sits still.
  const bullets: Array<{ e: EntityHandle; x: number; y: number; z: number; dx: number; dy: number; dz: number; age: number; hits: Set<EntityHandle> }> = [];

  if (player !== undefined && registerUpdate) {
    const root = player;
    registerUpdate((dt: number) => {
      // — FPS look via arrow keys (keyboard fallback: mouse-look needs pointer
      //   lock, which the embedded preview iframe disallows). —
      if (mode === 'fps') {
        const TURN = 2.4;
        if (keys['ArrowLeft']) lookYaw += TURN * dt;
        if (keys['ArrowRight']) lookYaw -= TURN * dt;
        if (keys['ArrowUp']) lookPitch = Math.min(1.2, lookPitch + TURN * 0.6 * dt);
        if (keys['ArrowDown']) lookPitch = Math.max(-1.2, lookPitch - TURN * 0.6 * dt);
      }

      // — movement + facing, per view mode —
      // intent axes: f = forward(+)/back(−), s = strafe right(+)/left(−). Arrows
      // alias WASD only in top-down; in FPS they steer the view (above).
      const am = mode !== 'fps';   // arrows-move (top-down only)
      const f = ((keys['KeyW'] || (am && keys['ArrowUp'])) ? 1 : 0) - ((keys['KeyS'] || (am && keys['ArrowDown'])) ? 1 : 0);
      const s = ((keys['KeyD'] || (am && keys['ArrowRight'])) ? 1 : 0) - ((keys['KeyA'] || (am && keys['ArrowLeft'])) ? 1 : 0);
      let mvx = 0, mvz = 0;
      if (mode === 'fps') {
        // look-relative; facing = look forward (front = local −Z; yaw 0 → (0,−1))
        const fwdX = -Math.sin(lookYaw), fwdZ = -Math.cos(lookYaw);
        const rgtX = -fwdZ, rgtZ = fwdX;          // +90° about Y → strafe right
        faceX = fwdX; faceZ = fwdZ;
        mvx = fwdX * f + rgtX * s; mvz = fwdZ * f + rgtZ * s;
      } else {
        // top-down: world-relative; facing = movement direction
        mvx = s; mvz = -f;                          // W → −Z, D → +X
        if (mvx !== 0 || mvz !== 0) { const l = Math.hypot(mvx, mvz); faceX = mvx / l; faceZ = mvz / l; }
      }
      if (mvx !== 0 || mvz !== 0) {
        const l = Math.hypot(mvx, mvz) || 1;
        const step = SPEED * dt;
        let nx = Math.max(-BOUND, Math.min(BOUND, px + (mvx / l) * step));
        let nz = Math.max(-BOUND, Math.min(BOUND, pz + (mvz / l) * step));
        // Kinematic bodies get no collision response vs static ones, so push the
        // player OUT of each ground obstacle's XZ circle (the tree trunk) from ANY
        // approach angle. Dynamic props are NOT walkBlockers → still get shoved.
        for (const o of walkBlockers) {
          const ox = nx - o.cx, oz = nz - o.cz;
          const d = Math.hypot(ox, oz);
          const minD = PLAYER_RADIUS + o.r;
          if (d < minD) {
            if (d > 1e-4) { nx = o.cx + (ox / d) * minD; nz = o.cz + (oz / d) * minD; }
            else { nx = o.cx + minD; }   // dead-center: shove out along +X
          }
        }
        px = nx; pz = nz;
      }

      // — jump (Space, edge-triggered; manual parabolic arc since kinematic) —
      const space = !!keys['Space'];
      if (space && !prevSpace && grounded) { vy = JUMP_V; grounded = false; }
      prevSpace = space;
      if (!grounded) {
        vy -= GRAV * dt;
        jumpY += vy * dt;
        if (jumpY <= PLAYER_Y) { jumpY = PLAYER_Y; vy = 0; grounded = true; }
      }

      // — drive the kinematic root: position + facing yaw (front = local −Z) —
      const yaw = Math.atan2(-faceX, -faceZ);
      const q = quat.eulerY(yaw);
      world.set(root, Transform, { pos: [px, jumpY, pz], quat: [q[0]!, q[1]!, q[2]!, q[3]!] });

      // — shoot (F, or left-click in FPS): kinematic bullet flies along `face` —
      shootCd -= dt;
      const fire = (keys['KeyF'] || wantShoot) && shootCd <= 0;
      wantShoot = false;
      if (fire) {
        shootCd = SHOOT_CD;
        // 3D shot direction, per mode:
        //   FPS:      full look dir (yaw + pitch) — crosshair can aim DOWN.
        //   Top-down: shotDir from the click (consumed once); falls back to
        //             facing if F was pressed without a recent click.
        // Origin: FPS from the eye, top-down from chest (≈ prop height ~0.5).
        let dirX = faceX, dirY = 0, dirZ = faceZ;
        let by = jumpY + 0.15;
        if (mode === 'fps') {
          const cp = Math.cos(lookPitch);
          dirX = -Math.sin(lookYaw) * cp; dirY = Math.sin(lookPitch); dirZ = -Math.cos(lookYaw) * cp;
          by = jumpY + EYE;
        } else if (shotDir) {
          dirX = shotDir.x; dirZ = shotDir.z; dirY = 0;
        }
        shotDir = null;   // one-shot snapshot consumed
        const bx = px + dirX * 0.6, byy = by + dirY * 0.6, bz = pz + dirZ * 0.6;
        const e = world.spawn(
          { component: Transform, data: { pos: [bx, byy, bz] } },
          { component: MeshFilter, data: { assetHandle: bulletMesh } },
          { component: MeshRenderer, data: { materials: [bulletMat] } },
          // RELIABLE CONTACT FIX (2026-06-10):
          //  ENGINE BUG (don't fix in engine — ubpa's repo): kinematic bodies
          //  don't honor `ccdEnabled` (rapier-physics-world-3d.ts:243-251 omits
          //  the setCcdEnabled call that the dynamic case has). So the bullet's
          //  setCcdEnabled call is a no-op and rapier uses DISCRETE collision.
          //  Workaround: a LARGER collider (radius 0.5 vs visible radius 0.2)
          //  so the bullet's contact zone overlaps every prop the moment its
          //  CENTER enters within `bullet_r + prop_r`. Even with frame-step ~0.4
          //  + dt jitter, the discrete check now ALWAYS lands inside the contact
          //  range for at least 1-2 frames → contact registers → prop pushed.
          //  ccdEnabled is left on the dynamic prop side (line ~256) where the
          //  engine DOES honor it — protects props from tunneling out of bounds.
          { component: RigidBody, data: { type: RigidBodyTypeValue.kinematic } },
          { component: Collider, data: { shape: ColliderShapeValue.sphere, radius: 0.5, friction: 0, restitution: 0.6 } },
        ).unwrap();
        bullets.push({ e, x: bx, y: byy, z: bz, dx: dirX, dy: dirY, dz: dirZ, age: 0, hits: new Set<EntityHandle>() });
      }
      // Advance + cull bullets (3D travel). Bullets fly THROUGH props (not
      // despawned on hit) so each prop gets several frames of kinematic-vs-
      // dynamic contact → reliable push. They despawn only on lifetime expiry.
      for (let i = bullets.length - 1; i >= 0; i--) {
        const b = bullets[i]!;
        b.age += dt;
        if (b.age > BULLET_LIFE) { world.despawn(b.e); bullets.splice(i, 1); continue; }
        b.x += b.dx * BULLET_SPEED * dt;
        b.y += b.dy * BULLET_SPEED * dt;
        b.z += b.dz * BULLET_SPEED * dt;
        world.set(b.e, Transform, { pos: [b.x, b.y, b.z] });
      }

      // — bullet↔target hit (rapier3d doesn't populate CollidingEntities →
      //   proximity-test for score/flash). Each (bullet, prop) pair scores at
      //   most ONCE — the per-bullet `hits` set prevents repeat scoring during
      //   the bullet's multi-frame pass-through. PHYSICS push is handled by
      //   the engine separately (bullet collider sweep contacting prop collider
      //   each step). Score is NOT gated by the flash window — every distinct
      //   prop hit counts. Flash visual is per-0.2s/prop to avoid thrashing.
      for (const b of bullets) {
        for (const fl of flashables) {
          if (b.hits.has(fl.e)) continue;
          const tr = world.get(fl.e, Transform);
          if (!tr.ok) continue;
          const fxp = tr.value.pos[0]!, fyp = tr.value.pos[1]!, fzp = tr.value.pos[2]!;
          const ex = b.x - fxp, ey = b.y - fyp, ez = b.z - fzp;
          if (ex * ex + ey * ey + ez * ez < HIT2) {
            b.hits.add(fl.e);
            const pts = targetPoints.get(fl.e);
            if (pts !== undefined) {
              score += pts;
              hud.setScore(score);
              spawnPopup('+' + pts, fxp, fyp + 0.8, fzp);
            }
            if (!flashUntil.has(fl.e)) {
              world.set(fl.e, MeshRenderer, { materials: [flashMat] });
              flashUntil.set(fl.e, 0.2);
            }
          }
        }
      }
      for (const [e, t] of flashUntil) {
        const nt = t - dt;
        if (nt <= 0) {
          world.set(e, MeshRenderer, { materials: [origMatOf.get(e)!] });
          flashUntil.delete(e);
        } else flashUntil.set(e, nt);
      }

      // — "+N" hit popups: handled by hud.floatScore (DOM overlay) at hit
      //   time, NOT a per-frame world-space billboard. See spawnPopup above
      //   for why (engine shadow-caster path projects every triangle mesh).

      // — camera, per view mode —
      if (mode === 'fps') {
        const qy = quat.create(); quat.fromAxisAngle(qy, [0, 1, 0], lookYaw);
        const qx = quat.create(); quat.fromAxisAngle(qx, [1, 0, 0], lookPitch);
        const cq = quat.create(); quat.multiply(cq, qy, qx);
        world.set(camera, Transform, { pos: [px, jumpY + EYE, pz], quat: [cq[0]!, cq[1]!, cq[2]!, cq[3]!] });
      } else {
        const a = 1 - Math.exp(-CAM_FOLLOW * dt);
        camX += (px - camX) * a;
        camZ += (pz + TOP_DZ - camZ) * a;
        world.set(camera, Transform, { pos: [camX, TOP_DY, camZ], quat: [topQ[0]!, topQ[1]!, topQ[2]!, topQ[3]!] });
      }
    });
  }
}
