import { get } from "./localization-runtime";
// ═══════════════════════════════════════════════════════════════════════════
// GENERATED FILE — LLM pre-generated NPC dialogue pools (docs/npc-rules.md).
// Generated by the studio agent BEFORE play; the game imports pure data and
// makes ZERO runtime LLM calls. To regenerate: re-read docs/npc-rules.md and
// rewrite this file (keep the exported shapes stable — npc-brain.ts and
// main.ts consume them).
// ═══════════════════════════════════════════════════════════════════════════

/** One preset question the player can pick from the talk menu. */
export interface TopicDef {
  id: string;      // stable topic id ('daily' | 'cup' | 'news' | 'gossip')
  label: string;   // menu entry text
  ask: string;     // the line the player actually says when picking it
}

/** Answer variants for one topic. Each variant = 1-2 NPC lines. */
export interface AnswerPool {
  base: ReadonlyArray<ReadonlyArray<string>>;
  /** mixed in once the NPC knows the player well (talkCount >= 3) */
  familiar?: ReadonlyArray<ReadonlyArray<string>>;
  /** favored after the player has WON the cup (facts.cupWins > 0) */
  champion?: ReadonlyArray<ReadonlyArray<string>>;
  /** favored after the player has LOST a match (facts.cupFalls > 0) */
  fell?: ReadonlyArray<ReadonlyArray<string>>;
  /** favored after the player has spectated an NPC duel (duelsWatched > 0) */
  watched?: ReadonlyArray<ReadonlyArray<string>>;
}

export interface NpcDialogue {
  greetFirst: ReadonlyArray<string>;      // first meeting
  greetFamiliar: ReadonlyArray<string>;   // talkCount >= 3
  greetChampion: ReadonlyArray<string>;   // player has won the cup
  topics: Readonly<Record<string, AnswerPool>>;
  farewells: ReadonlyArray<string>;
}

//  localized comment
export const TOPICS: ReadonlyArray<TopicDef> = [
  { id: 'daily', label: get("paopaotang.src/npc-dialogue.gen.ts:1870:ee4ba47dac"), ask: get("paopaotang.src/npc-dialogue.gen.ts:1885:0cdd1334d7") },
  { id: 'cup', label: get("paopaotang.src/npc-dialogue.gen.ts:1922:85115a17f8"), ask: get("paopaotang.src/npc-dialogue.gen.ts:1936:ffe6dcd916") },
  { id: 'news', label: get("paopaotang.src/npc-dialogue.gen.ts:1975:4887330508"), ask: get("paopaotang.src/npc-dialogue.gen.ts:1990:8e1ed7a37f") },
  { id: 'gossip', label: get("paopaotang.src/npc-dialogue.gen.ts:2032:75a1b39e31"), ask: get("paopaotang.src/npc-dialogue.gen.ts:2047:57da874690") },
];

//  localized comment
const PUDDING: NpcDialogue = {
  greetFirst: [
    get("paopaotang.src/npc-dialogue.gen.ts:2188:90a4263ff8"),
    get("paopaotang.src/npc-dialogue.gen.ts:2227:2d00c01578"),
    get("paopaotang.src/npc-dialogue.gen.ts:2269:252feaeeb6"),
  ],
  greetFamiliar: [
    get("paopaotang.src/npc-dialogue.gen.ts:2332:4cf86694d3"),
    get("paopaotang.src/npc-dialogue.gen.ts:2368:1082f5a5ab"),
    get("paopaotang.src/npc-dialogue.gen.ts:2405:4742eba05e"),
  ],
  greetChampion: [
    get("paopaotang.src/npc-dialogue.gen.ts:2468:333a39323d"),
    get("paopaotang.src/npc-dialogue.gen.ts:2505:fb99168cf0"),
  ],
  topics: {
    daily: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:2589:1801581927")],
        [get("paopaotang.src/npc-dialogue.gen.ts:2630:59c1fc50b0"), get("paopaotang.src/npc-dialogue.gen.ts:2665:27732f4855")],
        [get("paopaotang.src/npc-dialogue.gen.ts:2696:207d515957")],
      ],
      familiar: [
        [get("paopaotang.src/npc-dialogue.gen.ts:2767:74d325eaf7")],
        [get("paopaotang.src/npc-dialogue.gen.ts:2812:c0d9419f4d")],
      ],
    },
    cup: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:2892:3687a29768")],
        [get("paopaotang.src/npc-dialogue.gen.ts:2933:a0b5214b20"), get("paopaotang.src/npc-dialogue.gen.ts:2965:2cb6ed9af4")],
        [get("paopaotang.src/npc-dialogue.gen.ts:2993:ec54fdb932")],
      ],
      champion: [
        [get("paopaotang.src/npc-dialogue.gen.ts:3060:f80a57d1bb")],
        [get("paopaotang.src/npc-dialogue.gen.ts:3109:591ac247af")],
      ],
      fell: [
        [get("paopaotang.src/npc-dialogue.gen.ts:3176:e95db3fe63"), get("paopaotang.src/npc-dialogue.gen.ts:3204:69b7c3aa0e")],
        [get("paopaotang.src/npc-dialogue.gen.ts:3240:ec5fe644a6")],
      ],
      watched: [
        [get("paopaotang.src/npc-dialogue.gen.ts:3310:5972582423")],
      ],
    },
    news: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:3398:dea72f1ecf")],
        [get("paopaotang.src/npc-dialogue.gen.ts:3438:171c4f5495")],
        [get("paopaotang.src/npc-dialogue.gen.ts:3479:ef633f2c86")],
      ],
    },
    gossip: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:3565:4d08ab7b0b")],
        [get("paopaotang.src/npc-dialogue.gen.ts:3609:f3eee9b25e")],
        [get("paopaotang.src/npc-dialogue.gen.ts:3661:a3347ff93e")],
      ],
    },
  },
  farewells: [
    get("paopaotang.src/npc-dialogue.gen.ts:3738:e4353945db"),
    get("paopaotang.src/npc-dialogue.gen.ts:3763:2208ea8405"),
  ],
};

//  localized comment
const SODA: NpcDialogue = {
  greetFirst: [
    get("paopaotang.src/npc-dialogue.gen.ts:3902:c317838d11"),
    get("paopaotang.src/npc-dialogue.gen.ts:3946:40d2206ce0"),
    get("paopaotang.src/npc-dialogue.gen.ts:3987:cd60048118"),
  ],
  greetFamiliar: [
    get("paopaotang.src/npc-dialogue.gen.ts:4049:3367405190"),
    get("paopaotang.src/npc-dialogue.gen.ts:4089:63fe8898f3"),
    get("paopaotang.src/npc-dialogue.gen.ts:4126:f2141653f5"),
  ],
  greetChampion: [
    get("paopaotang.src/npc-dialogue.gen.ts:4186:dd7bfdb7db"),
    get("paopaotang.src/npc-dialogue.gen.ts:4225:e2594c162b"),
  ],
  topics: {
    daily: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:4321:f3321bdbad")],
        [get("paopaotang.src/npc-dialogue.gen.ts:4366:380d055135")],
        [get("paopaotang.src/npc-dialogue.gen.ts:4412:eca914bb8c")],
      ],
      familiar: [
        [get("paopaotang.src/npc-dialogue.gen.ts:4486:3767b522e7")],
        [get("paopaotang.src/npc-dialogue.gen.ts:4535:1f71cb5834")],
      ],
    },
    cup: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:4621:9cbc60ea46")],
        [get("paopaotang.src/npc-dialogue.gen.ts:4663:3c5d73fd32")],
        [get("paopaotang.src/npc-dialogue.gen.ts:4712:a5b2ce5500")],
      ],
      champion: [
        [get("paopaotang.src/npc-dialogue.gen.ts:4780:a32160f49e")],
        [get("paopaotang.src/npc-dialogue.gen.ts:4824:6ddb9165e9")],
      ],
      fell: [
        [get("paopaotang.src/npc-dialogue.gen.ts:4897:98f25d6116")],
        [get("paopaotang.src/npc-dialogue.gen.ts:4939:c920767ce7")],
      ],
      watched: [
        [get("paopaotang.src/npc-dialogue.gen.ts:5012:4f65f73aa3")],
      ],
    },
    news: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:5104:1830c01d79")],
        [get("paopaotang.src/npc-dialogue.gen.ts:5153:aec93da603")],
        [get("paopaotang.src/npc-dialogue.gen.ts:5200:f8c657df90")],
      ],
    },
    gossip: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:5291:e4654177f4")],
        [get("paopaotang.src/npc-dialogue.gen.ts:5337:03f6b52d5d")],
        [get("paopaotang.src/npc-dialogue.gen.ts:5381:754bba9237")],
      ],
    },
  },
  farewells: [
    get("paopaotang.src/npc-dialogue.gen.ts:5452:01fbc541ed"),
    get("paopaotang.src/npc-dialogue.gen.ts:5479:2ba8238c66"),
  ],
};

//  localized comment
const GRAPE: NpcDialogue = {
  greetFirst: [
    get("paopaotang.src/npc-dialogue.gen.ts:5633:2f4d94abed"),
    get("paopaotang.src/npc-dialogue.gen.ts:5663:977e67a79e"),
    get("paopaotang.src/npc-dialogue.gen.ts:5692:e9f2d5d195"),
  ],
  greetFamiliar: [
    get("paopaotang.src/npc-dialogue.gen.ts:5752:44115ea02f"),
    get("paopaotang.src/npc-dialogue.gen.ts:5786:3a0b473784"),
    get("paopaotang.src/npc-dialogue.gen.ts:5822:021018d928"),
  ],
  greetChampion: [
    get("paopaotang.src/npc-dialogue.gen.ts:5883:4a63a847b1"),
    get("paopaotang.src/npc-dialogue.gen.ts:5919:627bf08314"),
  ],
  topics: {
    daily: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:6008:ff14f9e3c9")],
        [get("paopaotang.src/npc-dialogue.gen.ts:6050:485226d178")],
        [get("paopaotang.src/npc-dialogue.gen.ts:6094:543bea76c9")],
      ],
      familiar: [
        [get("paopaotang.src/npc-dialogue.gen.ts:6160:78ed228390")],
        [get("paopaotang.src/npc-dialogue.gen.ts:6205:2dd62d6ee8")],
      ],
    },
    cup: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:6289:6efe792e97")],
        [get("paopaotang.src/npc-dialogue.gen.ts:6331:6e46b34612")],
        [get("paopaotang.src/npc-dialogue.gen.ts:6371:157f67291b")],
      ],
      champion: [
        [get("paopaotang.src/npc-dialogue.gen.ts:6441:6c13977682")],
        [get("paopaotang.src/npc-dialogue.gen.ts:6486:f888203013")],
      ],
      fell: [
        [get("paopaotang.src/npc-dialogue.gen.ts:6557:14c3b62713")],
        [get("paopaotang.src/npc-dialogue.gen.ts:6606:197df6cf47")],
      ],
    },
    news: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:6690:781cafb306")],
        [get("paopaotang.src/npc-dialogue.gen.ts:6735:ade682af41")],
        [get("paopaotang.src/npc-dialogue.gen.ts:6778:a2ba30448b")],
      ],
      watched: [
        [get("paopaotang.src/npc-dialogue.gen.ts:6851:8d543b551a")],
      ],
    },
    gossip: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:6943:c756827f2e")],
        [get("paopaotang.src/npc-dialogue.gen.ts:6983:3d7004220f")],
        [get("paopaotang.src/npc-dialogue.gen.ts:7024:66c205015e")],
      ],
    },
  },
  farewells: [
    get("paopaotang.src/npc-dialogue.gen.ts:7101:86bba1e928"),
    get("paopaotang.src/npc-dialogue.gen.ts:7124:fddf12e35e"),
  ],
};

//  localized comment
const BERRY: NpcDialogue = {
  greetFirst: [
    get("paopaotang.src/npc-dialogue.gen.ts:7266:7e7487745a"),
    get("paopaotang.src/npc-dialogue.gen.ts:7309:1f3ccb9a0b"),
    get("paopaotang.src/npc-dialogue.gen.ts:7352:d36d314c48"),
  ],
  greetFamiliar: [
    get("paopaotang.src/npc-dialogue.gen.ts:7417:449e8f05cb"),
    get("paopaotang.src/npc-dialogue.gen.ts:7451:a1a3f1788e"),
    get("paopaotang.src/npc-dialogue.gen.ts:7487:9685e60bb2"),
  ],
  greetChampion: [
    get("paopaotang.src/npc-dialogue.gen.ts:7544:63c938c4f1"),
    get("paopaotang.src/npc-dialogue.gen.ts:7584:97a7c7ff62"),
  ],
  topics: {
    daily: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:7669:f6f9aec862")],
        [get("paopaotang.src/npc-dialogue.gen.ts:7718:0cf147d696")],
        [get("paopaotang.src/npc-dialogue.gen.ts:7764:b2cc487bc1")],
      ],
      familiar: [
        [get("paopaotang.src/npc-dialogue.gen.ts:7839:7e543f3471")],
        [get("paopaotang.src/npc-dialogue.gen.ts:7883:9459a68061")],
      ],
    },
    cup: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:7971:4a80efec3b")],
        [get("paopaotang.src/npc-dialogue.gen.ts:8017:d16db598e4")],
        [get("paopaotang.src/npc-dialogue.gen.ts:8065:0c5ee1fd5e")],
      ],
      champion: [
        [get("paopaotang.src/npc-dialogue.gen.ts:8139:0a79a470d0"), get("paopaotang.src/npc-dialogue.gen.ts:8176:05c0be1c03")],
        [get("paopaotang.src/npc-dialogue.gen.ts:8207:de6c9edf5c")],
      ],
      fell: [
        [get("paopaotang.src/npc-dialogue.gen.ts:8273:620c172046"), get("paopaotang.src/npc-dialogue.gen.ts:8308:f4fc356e4b")],
        [get("paopaotang.src/npc-dialogue.gen.ts:8338:d75f4a6917")],
      ],
      watched: [
        [get("paopaotang.src/npc-dialogue.gen.ts:8414:e5cc1800e8"), get("paopaotang.src/npc-dialogue.gen.ts:8443:7e24af4438")],
      ],
    },
    news: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:8515:573b5e8d8e")],
        [get("paopaotang.src/npc-dialogue.gen.ts:8563:f87f580a24")],
        [get("paopaotang.src/npc-dialogue.gen.ts:8610:53709feb6f")],
      ],
    },
    gossip: {
      base: [
        [get("paopaotang.src/npc-dialogue.gen.ts:8696:90b18dc083")],
        [get("paopaotang.src/npc-dialogue.gen.ts:8739:f638cd3c96")],
        [get("paopaotang.src/npc-dialogue.gen.ts:8787:3f7b45cd75")],
      ],
    },
  },
  farewells: [
    get("paopaotang.src/npc-dialogue.gen.ts:8863:56a8ffbbf1"),
    get("paopaotang.src/npc-dialogue.gen.ts:8890:ece79cc613"),
  ],
};

//  localized comment
const GENERIC: NpcDialogue = {
  greetFirst: [get("paopaotang.src/npc-dialogue.gen.ts:9038:592337f5ee")],
  greetFamiliar: [get("paopaotang.src/npc-dialogue.gen.ts:9086:b16fb8b6a8")],
  greetChampion: [get("paopaotang.src/npc-dialogue.gen.ts:9124:06012def4a")],
  topics: {
    daily: { base: [[get("paopaotang.src/npc-dialogue.gen.ts:9176:ae124b8db8")]] },
    cup: {
      base: [[get("paopaotang.src/npc-dialogue.gen.ts:9234:98899e35c8")]],
      champion: [[get("paopaotang.src/npc-dialogue.gen.ts:9282:2cc0ae10e4")]],
      fell: [[get("paopaotang.src/npc-dialogue.gen.ts:9322:d7194644df")]],
    },
    news: { base: [[get("paopaotang.src/npc-dialogue.gen.ts:9379:31f2906ae2")]] },
    gossip: { base: [[get("paopaotang.src/npc-dialogue.gen.ts:9430:330b4b575b")]] },
  },
  farewells: [get("paopaotang.src/npc-dialogue.gen.ts:9484:fd2d120eaa")],
};

/*  localized comment */
export const NPC_DIALOGUE: Readonly<Record<string, NpcDialogue>> = {
  pudding: PUDDING, soda: SODA, grape: GRAPE, strawberry: BERRY,
};
export const GENERIC_DIALOGUE: NpcDialogue = GENERIC;
